### ISSUE TITLE
Download to cache

### ISSUE THREAD

**Issue by Lolozweipunktnull** [vfsfitvnm/ViMusic#293] opened 2022-09-09 21:25 UTC
### Feature description

Would it be possible to add a function to download a song to the cache to have it available offline later without having to play it once?

### Why do you want this feature?

I would like to have some songs available offline and it would make it more convenient for me.

**Comment by vfsfitvnm** [comment] 2022-09-10 05:39
Duplicate of #83

**Closed by vfsfitvnm** 2022-09-10 05:39 UTC
Labels: enhancement
