### ISSUE TITLE
Song cache resetting 

### ISSUE THREAD

**Issue by Blitzbombeater** [vfsfitvnm/ViMusic#1310] opened 2023-11-10 04:13 UTC
### Steps to reproduce the bug

Download 1000+ songs 

### Expected behavior

The songs stay and work permanently 

### Actual behavior

Song cache resets even on unlimited after reaching more than 1000 songs 

### Screenshots/Screen recordings

![Screenshot_2023-11-10-17-03-47-07_6f55a3c4de83481ebdee1685416eed82](https://github.com/vfsfitvnm/ViMusic/assets/150330760/46527a0b-607f-4dd8-ba02-004d351fd01a)
![IMG_20231110_170655](https://github.com/vfsfitvnm/ViMusic/assets/150330760/8881ef11-7c81-4878-b61a-e6ae092ad27b)

### ViMusic version

 0.5.4

### Android version

Android 12-13

### Additional information

Phone model oppo a74 5g Ram 6gb storage 128gb
OS Color OS 13.0

**Comment by charanravi-online** [comment] 2023-11-15 07:50
Experiencing the exact same issue with the latest version (v0.5.4) on my OnePlus 9RT 8GB RAM, 128GB Storage, running Color OS13.1

**Comment by bartoostveen** [comment] 2023-11-15 10:01
According to [the docs](https://developer.android.com/training/data-storage/app-specific#internal-remove-cache), the system cleans up cache files on it's own without notice, presumably when the system needs more space or cache usage reaches an arbitrary limit.

I guess it would be a good solution to provide a setting for the cache location, because using 'regular' app storage is more trustworthy.

**Comment by Blitzbombeater** [comment] 2023-11-15 10:35
My guess out of the two is that Google is probably seeing the app as a PUP and removing the cache due to its large cache size because my storage is far from super close to being full having 26 gigs free so id place my bets on cache

**Comment by charanravi-online** [comment] 2023-11-16 04:01
@Blitzbombeater just an FYI, I have around 17 gigs free (which I feel is sufficient).

**Comment by Nikhilkranthi** [comment] 2023-11-25 18:02
Yep +1. Facing the same issue
The offline section vanishes every day. Have plenty of free space available

**Comment by vfsfitvnm** [comment] 2024-01-06 13:11
Duplicate of #289

**Closed as not planned by vfsfitvnm** 2024-01-06 13:11 UTC
Labels: bug, duplicate
