### ISSUE TITLE
Alternative layout for global users

### ISSUE THREAD

**Issue by knightmob** [vfsfitvnm/ViMusic#600] opened 2022-11-07 15:10 UTC
Hello! I've been using ViMusic as my go to YouTube music alternative app, and its really good, ui is focused on simplicity + the cache saving thing is brilliant, just one concern though, recently I updated ViMusic to latest version and it appears the layout changes, I know the layout is reserve for local users only, but can I ask for a global layout? for global users? It's really good + very interactive apk not like any other third party app out there, the only problem is the new layout, I'm actually fine about the vertical layout though, it looks cool, the only problem is the proper placing of word in every category like the right position instead of left and also the search is place in the right. I'm not really asking for a complete transformation though, I'm just requesting an old alternative layout for global users like me that are not arabic. Overall nice app! Nice passion you have dev, hope you'll listened to my request, and thank you for reading my message.

**Comment by vfsfitvnm** [comment] 2022-11-08 07:08
Duplicate of #390 and #394

**Closed by vfsfitvnm** 2022-11-08 07:08 UTC
