### ISSUE TITLE
Feature to import playlist from Spotify and YT

### ISSUE THREAD

**Issue by meetp11** [vfsfitvnm/ViMusic#598] opened 2022-11-07 03:22 UTC
### Feature description

An option in the playlist section to import playlists from different platforms like spotify and YT. There's an app called BlackHole by Ankit Sangwan(shout out to him) that does this. It works like an charm and is open source so I tought it might help get the feature in VI music too.

### Why do you want this feature?

I love the app and I want to use it more the thing is I have tons of songs on my spotify and YT that is just a pain in the butt to manually search and play everytime i want to listen to music. It would be so much useful if i could just import the playlists from Spotify and YT to Vi music.

**Comment by vfsfitvnm** [comment] 2022-11-07 05:39
Duplicate of #462

**Closed by vfsfitvnm** 2022-11-07 05:39 UTC
Labels: enhancement
