### ISSUE TITLE
Show device files for offline music

### ISSUE THREAD

**Issue by Lipu47** [vfsfitvnm/ViMusic#331] opened 2022-09-23 05:19 UTC
### Feature description

You can add an option to listen to the music file in our device memory like it does in other music streaming platform.
![IMG_20220923_104810](https://user-images.githubusercontent.com/113649785/191896280-4c8fad4a-187c-47f4-b776-57bd69a697a5.jpg)
You can add that option after offline folder.
![IMG_20220923_102759](https://user-images.githubusercontent.com/113649785/191894681-83fea189-2c02-43b1-9ba4-bfd6a6370f37.jpg)

### Why do you want this feature?

Everything is great and beautiful. Like other music streaming platform you can also add some additional features like "Show device music files". We have download some of songs in our device but I can't access it in vimusic.

**Comment by vfsfitvnm** [comment] 2022-09-23 05:43
Duplicate of #57

**Closed by vfsfitvnm** 2022-09-23 05:43 UTC
Labels: enhancement
