### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by briantgosling** [vfsfitvnm/ViMusic#605] opened 2022-11-08 11:12 UTC
### Feature description

add recommendations in searching songs and add refresh scroll on quick pick option

### Why do you want this feature?

its great

**Comment by vfsfitvnm** [comment] 2022-11-08 11:19
> add recommendations in searching songs

Duplicate of #569 

> refresh scroll on quick pick option

They already refresh when a there's a new trending song (see #413)

**Closed by vfsfitvnm** 2022-11-08 11:19 UTC
Labels: enhancement
