### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Harimsd** [vfsfitvnm/ViMusic#260] opened 2022-08-28 05:18 UTC
### Feature description

Please add creating profile option to access playlist

### Why do you want this feature?

I want to use my playlist in different devices

**Comment by NR8124** [comment] 2022-08-28 05:29
U have option to export the whole db and then import the same in another device/reinstalling app...

**Comment by jerryop** [comment] 2022-08-28 05:43
I think spotify playlist import feature will be a great if it possible

**Comment by NR8124** [comment] 2022-08-28 06:32
@jerryop  it Would be better if u open a new issue on your feature request.. rather then commenting on random issues

Also check whether this feature is being already asked or not

**Comment by vfsfitvnm** [comment] 2022-08-28 08:26
Duplicate of #211 or #97

**Closed by vfsfitvnm** 2022-08-28 08:26 UTC
Labels: enhancement
