### ISSUE TITLE
Auto scroll Queue

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#176] opened 2022-08-06 19:51 UTC
### Feature description

The queue should be auto scrolled upside/downside when we r shifting a song by holding it..

### Why do you want this feature?

When  song is at the bottom but we want it to be near to top of list
Its doesn't work as we wanted it to.. when trying to reorder the list by holding the song and do it

### Additional information

So auto scrolling queue will help in such case

As this kind feature is already exists...

**Comment by vfsfitvnm** [comment] 2022-08-06 20:02
Unfortunately there's no way to do that yet.

**Comment by Malopieds** [comment] 2022-08-07 07:18
Appears to have been done [here](https://github.com/aclassen/ComposeReorderable)
I have not fully checked the code but there are some ideas [here too](https://stackoverflow.com/a/68324351)

**Comment by vfsfitvnm** [comment] 2022-08-07 08:08
The repo you linked doesn't work when items don't have a key. But most importantly, it works because item positions are updated while the drag is happening (again, this is bad for performance if items don't have a key). This isn't something you want to do when you have disk based data. The workaround would require copying the whole list - not something I'm willing to do now.

My implementation doesn't need any of this, and it would support the scrolling if only the jetpack compose team made a certain parameter public (they already replied "they are not planning to do so") - so now I also need to fork and maintain another LazyList. Not sure it's worth.

**Comment by vfsfitvnm** [comment] 2022-08-07 08:17
I also found an old video of how that repository worked (probably is way better now) - definitely unusable, that's why I didn"t use it.

https://user-images.githubusercontent.com/46219656/183281824-0ddcd069-3000-4ac4-82d8-a4050cf9699c.mp4

**Comment by NR8124** [comment] 2022-08-07 08:21
> I also found an old video of how that repository worked (probably is way better now) - definitely unusable, that's why I didn"t use it.


The current one is far better then this
The only concern is tha auto scrolling part

**Comment by vfsfitvnm** [comment] 2022-08-07 20:44
To add more: the problem is not related to the autoscrolling thing, but we are moving items in a LazyColumn. When the item gets dragged "too far" (i.e. after scrolling), it will disappear from the screen because that's the nature of a LazyColumn. The private LazyColumn implementation has a parameter which allows an item to be pinned, i.e. to NOT get disposed.

**Comment by NR8124** [comment] 2022-08-08 03:59
Ok lets forgot the dragging part.. our concern was about taking a song at bottom to top

So for that .. what if in tap and hold menu of song QUEUE there one more option i.e. PLAY NEXT
So it will automatically shifted to upside

**Comment by vfsfitvnm** [comment] 2022-08-12 13:09
Another idea would be replacing the drag handle with a button (e.g. an arrow) which is basically "play next"

**Comment by NR8124** [comment] 2022-08-12 13:14
It would be great 🙌👍 but keep the dragging feature along with moving to top on single tap

**Comment by NR8124** [comment] 2022-08-12 13:35
>a button (e.g. an arrow)

what about something like this as a icon @vfsfitvnm 
![image](https://user-images.githubusercontent.com/88180887/184364429-d359b69b-5726-43fb-892c-742c60a63e13.png)

**Comment by vfsfitvnm** [comment] 2022-08-16 20:58
It took several hours of frustration to finally have an acceptable result:

https://user-images.githubusercontent.com/46219656/184983766-8ee289c3-3211-4a89-a9eb-2c48225400c8.mp4

**Closed** 2022-08-16 21:13 UTC
Labels: enhancement
