### ISSUE TITLE
All data gone

### ISSUE THREAD

**Issue by yephny** [vfsfitvnm/ViMusic#320] opened 2022-09-19 09:14 UTC
I had multiple albums/playlists saved and songs favorited. Then, I

1. launched the app,
2. searched for a song,
3. hit `go to album`,
which caused the app to restart. When it reloaded, all my data was gone: no song history, favorites, or saved playlists. Though, it looks like my data is still there, as it shows in the settings that the app has 94 MB of user data and 28 MB of cache.

ViMusic 0.4.3 from F-Droid on LineageOS, Android 10.

**Comment by vfsfitvnm** [comment] 2022-09-19 11:20
> which caused the app to restart

I need to know what's the album you visited.
Also, did the app crash? If so, please provide a logcat

> When it reloaded, all my data was gone: no song history, favorites, or saved playlists. 

This is odd. Would you share your database (Settings > Backup & Restore)?

**Comment by yephny** [comment] 2022-09-19 13:00
[Looks](https://upload.disroot.org/r/cYL5zonk#sBGPbJyyDu5wrislDqTB+ijpp3bGKLxBaUCq4/CYQ9I=) like it's really all gone.

**Comment by yephny** [comment] 2022-09-20 05:38
If you haven't downloaded it, the file will be deleted in a few hours.

**Comment by vfsfitvnm** [comment] 2022-09-20 07:37
Unfortunately I can't do much as I can't reproduce it. I visited that album but no crash occurred (you also didn't provide a logcat, so I can't verify it as well). Moreover, the fact that everything was deleted means there isn't a bug in my code, but there's something wrong happening in a lower layer. Closing until further information is reported.

**Closed by vfsfitvnm** 2022-09-20 07:37 UTC
Labels: bug, can't reproduce

**Comment by yephny** [comment] 2022-09-20 10:26
My phone does not report crashes unless I install an app like Scoop to catch the stack trace, so I don't have any crash logs. I'm not sure what I can do to reproduce the issue.

**Comment by yephny** [comment] 2022-09-20 10:34
There are files in `/data/user/0/it.vfsfitvnm.vimusic/files/coil` dating back to July 22, however.

**Comment by vfsfitvnm** [comment] 2022-09-20 11:24
If you didn't reboot your device, you can still grab the `logcat` using the `adb` command line tool or literally any logcat reader application
