### ISSUE TITLE
Refresh Linked Playlist

### ISSUE THREAD

**Issue by emkay5771** [vfsfitvnm/ViMusic#290] opened 2022-09-09 18:49 UTC
### Feature description

After adding a playlist from a youtube music link, add the capacity to refresh or sync it when songs are added and removed.

### Why do you want this feature?

Makes the experience of syncing playlist much simpler than removing and adding it each time there is an update to the playlist.

**Comment by vfsfitvnm** [comment] 2022-09-09 20:09
Duplicate of #196

**Closed by vfsfitvnm** 2022-09-09 20:09 UTC
Labels: enhancement
