### ISSUE TITLE
there is still bacckground music when you quit app

### ISSUE THREAD

**Issue by damiansangels** [vfsfitvnm/ViMusic#309] opened 2022-09-16 15:58 UTC
### Steps to reproduce the bug

1. start playing some music
2. quit quit app by open app changer and swiping on app
3. the music is still playin even though app quit

### Expected behavior

it should stop playing music when app is completely closed

### Actual behavior

It still playing the song

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/113709403/190679850-5586ff69-e7af-40ed-a02c-0bc296fde5bf.mp4

### ViMusic version

0.4.3

### Android version

12 one ui 4

### Additional information

I love the layout of this app so much but this is something that i have never seen before and shouldn't be here. It would be great if you can fix it. I would use this app everyday if this issue was fixed. also it would be cool if you could personalize what you see when you open the app like maybe being able to edit the layout and move things around. also it would cool it there was a visualizer

**Comment by damiansangels** [comment] 2022-09-16 15:59
thank you for your time

**Comment by vfsfitvnm** [comment] 2022-09-16 16:29
Duplicate of #305 and others

**Closed by vfsfitvnm** 2022-09-16 16:29 UTC
Labels: bug

**Comment by damiansangels** [comment] 2022-09-16 16:36
So is it being worked on
