### ISSUE TITLE
Saving music (or playlist) to cash without listening it

### ISSUE THREAD

**Issue by liponex** [vfsfitvnm/ViMusic#280] opened 2022-09-04 19:24 UTC
### Feature description

Possiblity to download music (or playlist) using button

### Why do you want this feature?

Music automatically adds to playlist while you listening to, but sometimes you need to download some to listen it later. Now to do it, you must listen to all of them from being to the end. Instead it will be great to load it by pressing special button for one song or even whole playlist.
Also that will be great if some of playlists you can mark as favorite to prevent deleting songs from cache.

**Comment by vfsfitvnm** [comment] 2022-09-04 19:27
Duplicate of #83

**Closed by vfsfitvnm** 2022-09-04 19:27 UTC
Labels: enhancement
