### ISSUE TITLE
Multi language support.

### ISSUE THREAD

**Issue by IZK115** [vfsfitvnm/ViMusic#550] opened 2022-10-29 20:27 UTC
First of all, thank you very much to the creators for such a wonderful application, I was reading the proposals but (at least I couldn't see something similar).
The option to be able to use the application in Spanish, for example, since for me it is a super app and I understand some things about English but I would like to share it with my friends who do not know English.

**Comment by vfsfitvnm** [comment] 2022-10-30 05:37
Duplicate of  #100

**Closed by vfsfitvnm** 2022-10-30 05:37 UTC
