### ISSUE TITLE
Source Error

### ISSUE THREAD

**Issue by Vsrq** [vfsfitvnm/ViMusic#96] opened 2022-07-13 05:23 UTC
### Steps to reproduce the bug

Bug seems to appear on random songs.

### Expected behavior

The song should play

### Actual behavior

The song does not play & a thumbnail does not show.

### Screenshots/Screen recordings

![Screenshot_20220713-011732](https://user-images.githubusercontent.com/109198893/178656863-fdac6508-e703-4f6c-8ced-e0acf12072bd.jpg)

### ViMusic version

0.1.7

### Android version

Android 12

### Additional information

Samsung Galaxy S20 FE 5G
OneUI 4.1

**Comment by vfsfitvnm** [comment] 2022-07-13 07:25
Would you try the latest debug apk (https://github.com/vfsfitvnm/ViMusic/suites/7329358552/artifacts/296655890) and see if it still occurs? If so, would you send me the logcat?

**Comment by Vsrq** [comment] 2022-07-13 07:29
I installed the debug app and the songs that original had the source error are playing perfectly!

**Comment by vfsfitvnm** [comment] 2022-07-13 08:58
@Vsrq 
Good to know, however I don't know what happened - I cannot reproduce the issue with the song you provided :/

I'll close this for now assuming it is fixed, please reopen if it occurs with the debug apk (however, the next release should coming very soon!).

**Closed by vfsfitvnm** 2022-07-13 08:58 UTC
Labels: bug
