### ISSUE TITLE
Slide navigation 

### ISSUE THREAD

**Issue by Bolsderac** [vfsfitvnm/ViMusic#575] opened 2022-11-03 20:35 UTC
### Feature description

Hi,
Thank you for this very great app'.
It could be usefull to be able to slide right and left for navigation between chapters.
Bolsderac

### Why do you want this feature?

For one hand navigation.

**Comment by vfsfitvnm** [comment] 2022-11-03 20:46
Duplicate of #398

**Closed by vfsfitvnm** 2022-11-03 20:46 UTC
Labels: enhancement
