### ISSUE TITLE
This is going to be the best feature if possible.

### ISSUE THREAD

**Issue by Harkusiii** [vfsfitvnm/ViMusic#75] opened 2022-07-03 12:11 UTC
### Feature description

Can I have a request? Can you please add the offline files in the app too?

### Why do you want this feature?

For better usage.

### Additional information

If this feature is added to the app, I think many people will use it.

**Comment by vfsfitvnm** [comment] 2022-07-03 12:43
Duplicate of #57

**Closed by vfsfitvnm** 2022-07-03 12:43 UTC
Labels: duplicate, enhancement
