### ISSUE TITLE
 A feature to play local storage music 

### ISSUE THREAD

**Issue by Fariie** [vfsfitvnm/ViMusic#628] opened 2022-11-12 17:07 UTC
### Feature description

Hey... I just created github ac to tell you about this feature. Please add a feature to play songs in our phones internal storage.

### Why do you want this feature?

It would be so helpful if you have this feature.many people live to see this feature just like me.there are many songs in my internal storage but i dont have a good music player to play that. Please add this feature in the new update.my kindly request 😔

**Comment by vfsfitvnm** [comment] 2022-11-12 17:15
Duplicate of #57

**Closed by vfsfitvnm** 2022-11-12 17:15 UTC
Labels: enhancement
