### ISSUE TITLE
Song cahce is getting cleared

### ISSUE THREAD

**Issue by iamabing01** [vfsfitvnm/ViMusic#351] opened 2022-09-29 03:10 UTC
### Steps to reproduce the bug

The cached songs are getting cleared after a day. I have set the max value to 1GB. Even after that, it's getting cleared.  This issue is only with song, the image cache is still there.

### Expected behavior

Shouldn't the app save the cache till they are manually cleared or when the storage quota is full?

### Actual behavior

Instead, they get cleared. When I try to play without the internet it shows an 'Unexpected Error' that's when you know the cache got cleared. 

### ViMusic version

v0.4.3

### Android version

Android 11

**Comment by vfsfitvnm** [comment] 2022-09-29 05:17
Duplicate of #289

**Closed by vfsfitvnm** 2022-09-29 05:17 UTC
Labels: bug
