### ISSUE TITLE
Lyrics Sync to Music

### ISSUE THREAD

**Issue by qolbudr** [vfsfitvnm/ViMusic#126] opened 2022-07-24 08:43 UTC
### Feature description

**Some Implementation**
I found a repo that provide how to get synced lyric with time (maybe you can use the time to sync with the audio) it use cloudflare workers to find the lyric

Here is the repo:
[https://github.com/lujjjh/lyrics-api](https://github.com/lujjjh/lyrics-api)

**Step to Reproduce**
1. Use that repo as a backend to find song lyric
2. In your application sync the time that provided in the lyric with music audio

**Expected Behaviour**
Show synced lyrics with the audio as spotify look a like

### Why do you want this feature?

just wanna sing a long with the synced lyric hahaha :)

**Comment by vfsfitvnm** [comment] 2022-07-24 09:16
Unfortunately that project doesn't add much value to what I already know.
Also, please don't open a new issueb - you can just leave a comment here #121

**Comment by qolbudr** [comment] 2022-07-24 09:26
so its too clear to be implemented ?

**Comment by JustNaturalCake** [comment] 2022-08-03 09:21
I was wondering if this could get added aswell, could maybe add an option "Lyrics Sync" or some sort of name inside settings > player and audio.

**Comment by JustNaturalCake** [comment] 2022-08-03 09:46
![20220803_114556_076](https://user-images.githubusercontent.com/108516353/182578497-ea79f64a-fe5b-48c4-a04e-65be081b588b.jpg)
Something like this?

**Comment by vfsfitvnm** [comment] 2022-08-03 09:51
@JustNaturalCake The problem is not adding a setting option, but safely obtaining the synchronized lyrics and parse them. https://github.com/vfsfitvnm/ViMusic/issues/121#issuecomment-1193299991

**Comment by qolbudr** [comment] 2022-08-03 10:29
> Is the api to find lyrics not open source?

yes i think this repo https://github.com/lujjjh/lyrics-api clearly open source and possible to be implemented

**Comment by vfsfitvnm** [comment] 2022-08-03 10:54
No, I just can't use that project - it's not an android library. Also, its code is open source, but the services it uses are not. It fetches chinese music services

**Comment by JustNaturalCake** [comment] 2022-08-03 10:59
It is desktop though so yeah it wont work indeed

**Comment by qolbudr** [comment] 2022-08-03 11:03
> No, I just can't use that project - it's not an android library. Also, its code is open source, but the services it uses are not. It fetches chinese music services

no, i mean just use the repo and upload it to the server and use it as endpoint api to fetch synced lyrics.

i will help to find repo how to add synced lyrics to your app using kotlin

and its true that it using chinese music service but the lyrics is not chinese alphabet, and i think its no problem

![Screenshot_2022-08-03-17-59-25-87_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/61232165/182593044-84cdcc5c-b536-4689-ad05-eea37e913895.jpg)

**Comment by vfsfitvnm** [comment] 2022-08-03 11:08
Oh, I didn't see it also offered that - I was only looking at the source code. This is a good thing, but there still are many concerns regarding the song matching (and its speed). I'll do some checks

**Comment by qolbudr** [comment] 2022-08-03 11:18
> Oh, I didn't see it also offered that - I was only looking at the source code. This is a good thing, but there still are many concerns regarding the song matching (and its speed). I'll do some checks

found this lrc parser, check this out

https://github.com/authorfu/LrcParser

**Comment by JustNaturalCake** [comment] 2022-08-03 11:25
I feel like some people prefer just normal text that doesnt highlight or move aswell but i do prefer it being synced

**Comment by vfsfitvnm** [comment] 2022-08-03 11:28
Yeah, at this point the parsing shouldn't be hard.

https://github.com/lujjjh/lyrics-api accuracy looks fine (it may be imprecise with extended mixes) but it's a bit slow - not a deal breaker tho.

**Comment by vfsfitvnm** [comment] 2022-08-03 15:45
Work in progress

https://user-images.githubusercontent.com/46219656/182651628-15e3159d-e356-43ec-9806-84dc873d1654.mp4

**Comment by qolbudr** [comment] 2022-08-03 15:47
> Work in progress
> 
> https://user-images.githubusercontent.com/46219656/182651628-15e3159d-e356-43ec-9806-84dc873d1654.mp4

cool can't wait in release version 🔥🔥

**Comment by vfsfitvnm** [comment] 2022-08-03 19:29
https://github.com/vfsfitvnm/ViMusic/suites/7653661759/artifacts/318681656

You can try the debug apk here. Please let me know if you face crashes.

**Comment by nateRiver111** [comment] 2022-08-03 21:21
The lyrics of [this](https://music.youtube.com/watch?v=3iZliEu-iFc), [this](https://music.youtube.com/watch?v=z2qoihbzc3E), [this](https://music.youtube.com/watch?v=NhsK5WExrnE) and [this](https://music.youtube.com/watch?v=26GJ9gIn820) song makes the app crash.

**Comment by qolbudr** [comment] 2022-08-04 00:23
> The lyrics of [this](https://music.youtube.com/watch?v=3iZliEu-iFc), [this](https://music.youtube.com/watch?v=z2qoihbzc3E), [this](https://music.youtube.com/watch?v=NhsK5WExrnE) and [this](https://music.youtube.com/watch?v=26GJ9gIn820) song makes the app crash.

for this bug except bee gees song, try to add fallback when the time duration is only contains 1 digit try to add zero in front of that.

Example :
[00:04.2] to be [00:04.02]

PS: i still didnt know why it crash on bee gees song 😅

and then i found bug again while show synced lyrics and it is still fetching, when i click next song the app sometime crash

**Comment by vfsfitvnm** [comment] 2022-08-04 06:27
> and then i found bug again while show synced lyrics and it is still fetching, when i click next song the app sometime crash

Thia one should be fixed already in the latest debug build

**Comment by qolbudr** [comment] 2022-08-04 08:25
im add more lyrics provider here :
https://lyrics-api.qolbudr.workers.dev/?artist=stand%20here%20alone&name=kita%20lawan%20mereka

or if you wanna see the repo you can check it here:
https://github.com/qolbudr/lyrics-api/

**Comment by vfsfitvnm** [comment] 2022-08-04 10:57
@qolbudr Thanks for that.

At this point I'm gonna fork it too so we can:
- fix badly formatted lrc (netease has plenty of them)
- remove any header we don't need (`[00:00.00] 作词`)
- remove the ip logging (which you already did lol)
- remove the github source (it only has 1 lrc file afaik)

Also, I don't think lyricsify should be kept, it only has few lyrics, it would only add some overhead.

Honestly, netease has the most complete catalog out there and it is accessible from any IP (QQ requires a chinese IP).

Also, I think I could just directly implement a netease api, it would be faster and more accurate.

**Comment by qolbudr** [comment] 2022-08-04 11:01
> Also, I don't think lyricsify should be kept, it only has few lyrics, it would only add some overhead.

please keep it, it have completely indonesian song and some western song lyric hahaha 😅

**Comment by vfsfitvnm** [comment] 2022-08-04 16:53
Note to self: QQProvider
```kt
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.client.request.header
import io.ktor.client.request.parameter
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement

object QQProvider {
    private const val baseUrl = "https://c.y.qq.com"

    private suspend fun lyrics(client: HttpClient, id: Int): Result<String?>? {
        return runCatching {
            client.get("$baseUrl/lyric/fcgi-bin/fcg_query_lyric_new.fcg") {
                header("referer", baseUrl)

                parameter("musicid", id)
                parameter("format", "json")
                parameter("nobase64", 1)
                parameter("outCharset", "utf-8")
            }.body<LyricsResponse>().lyric?.trimBloat()
        }.recoverIfCancelled()
    }

    override fun get(client: HttpClient, artist: String, title: String): Result<String?>? {
        fun String.decode() = replace('+', ' ')

        val songs = client.get("$baseUrl/lyric/fcgi-bin/fcg_search_pc_lrc.fcg") {
            parameter("SONGNAME", title)
            parameter("SINGERNAME", artist)
        }.body<SearchResponse>().cmd.songs

        val titleLowercase = title.lowercase()
        val artistLowercase = artist.lowercase()

        return songs.findLast { song ->
            song.name.lowercase().decode() == titleLowercase &&
                song.artist.lowercase().decode() == artistLowercase
        }?.id?.let {
            lyrics(client, it)
        }
    }
}

@Serializable
@SerialName("command-lable-xwl78-qq-music")
data class SearchResponse(
    @XmlElement(true) val cmd: Cmd
) {
    @Serializable
    @SerialName("cmd")
    data class Cmd(
        @SerialName("songcount") @XmlElement(true) val songCount: Int,
        @XmlElement(true) val songs: List<SongInfo>,
    ) {
        @Serializable
        @SerialName("songinfo")
        data class SongInfo(
            @SerialName("id") val id: Int,
            @SerialName("name") @XmlElement(true) val name: String,
            @SerialName("singername") @XmlElement(true) val artist: String,
            @SerialName("albumname") @XmlElement(true) val album: String,
        )
    }
}

@Serializable
data class LyricsResponse(val lyric: String?)
```

**Comment by vfsfitvnm** [comment] 2022-08-04 17:20
Uhm, I still don't know if I can implement this feature at the moment.

There are only two viable and decent providers: **qq** and **netease** - they both have a great catalogue.

**qq** seems to have better lyrics, BUT you can only search a lrc by the artist name and song title.
If a song has either a featuring or has different versions or is a remix or whatsoever, then it won't find the lyrics.
The lyrics have html character entities (-.-).

**netease** lyrics seem to be slightly more imprecise, BUT the matching is also more accurate. The lyrics do not always follow the correct format (-.-).

**Comment by qolbudr** [comment] 2022-08-04 17:56
no problem, if the synced lyrics not available for featuring or remix version

**Comment by vfsfitvnm** [comment] 2022-08-04 18:11
I'm not used to ship a feature that works half of the times. Also, I still have to give a shot at netease.

Keep in mind youtube music will add synchronized lyrics, eventually. Maybe the process can be accelerated somehow.

The last resort consists in trying to reverse engineer i.e. instagram or any other application that has a really good synchronized lyrics database

**Comment by qolbudr** [comment] 2022-08-04 19:05
maybe can you just add it as experimental feature it would be nice, and i discover in debug version that synced lyrics can be added manually by editing that and its awesome

**Comment by BluePixel4k** [comment] 2022-08-06 09:26
> maybe can you just add it as experimental feature it would be nice

I think so too, you shouldn't just throw away this function at this stage. After all, it already has added value :)

**Comment by vfsfitvnm** [comment] 2022-08-06 17:54
Please try the latest debug build (https://github.com/vfsfitvnm/ViMusic/suites/7696931775/artifacts/321682405). Make sure the delete the old debug app data.

There's a third provider, **kugou**, which I found out to be superior to qq and netease in term of searchability and lyrics quality.
However, it may contain html character entities - I just replace `&amp;` to `'` at the moment, please let me know if you see weird characters.

**Comment by nateRiver111** [comment] 2022-08-07 15:08
Tested it, I didn't experience any crashes or mismatched songs like I did with the others providers.
There are a few songs that are slightly out of sync but that should be a problem no matter the provider you use and everyone that want synced lyrics should be aware of that, the edit button is there to fix I would suggest to add a way to add, for example, +1 sec to all timestamp.

P.S. can the fetch of the lyrics be automatic when you're caching a new songs. I mean when you get data, metadata, thumbnails add there static and synced lyrics so it gets cached too whiteout user interaction.

**Comment by vfsfitvnm** [comment] 2022-08-07 20:56
> I would suggest to add a way to add, for example, +1 sec to all timestamp

I doubt this is a scalable solution, i.e. we should understand if these delays are systematic first.

> can the fetch of the lyrics be automatic when you're caching a new songs

Nope

**Comment by vfsfitvnm** [comment] 2022-08-09 15:06
Closing as completed. However you can still report problems or whatever related to synchronized lyrics here.

Ideally, we could remove the "static" lyrics fetched from youtube and just show the ones from kugou: in this case the synchronization would stop when the user tries to scroll the lyrics (and a button to re-sync would appear). This would semplify the codebase a bit. Let me know what you think.

**Closed by vfsfitvnm** 2022-08-09 15:06 UTC
Labels: enhancement

**Comment by BluePixel4k** [comment] 2022-08-09 17:46
> Ideally, we could remove the "static" lyrics fetched from youtube and just show the ones from kugou: in this case the synchronization would stop when the user tries to scroll the lyrics (and a button to re-sync would appear).

That sounds like a great solution. 👌

**Comment by habnixzutun** [comment] 2022-12-21 22:41
Hey, maybe I´m a little late but how do you think about a tool to synchronize lyrics yourself inside the app. Less than 1% of the songs I listen to don´t get synchronized lyrics from kugou.com.  I wrote myself a small python program for that but it´s pretty annoying to upload the latest database to onedrive, edit it on my pc and get it back on my phone again.

**Comment by retorquere** [comment] 2023-08-31 09:56
Has this made it to a release, or only debug versions? Would love to use this.
