### ISSUE TITLE
Integrarion MicroG

### ISSUE THREAD

**Issue by DarkenDevil** [vfsfitvnm/ViMusic#543] opened 2022-10-29 09:47 UTC
### Feature description

Please integrate microG feature so i can synchronise my fav song into vimusic

### Why do you want this feature?

Because it bothers me when i search song one by one.. So if synchronised microG my playlist can be appear there

### Additional information

-

**Comment by vfsfitvnm** [comment] 2022-10-29 09:56
Duplicate of #354

**Closed by vfsfitvnm** 2022-10-29 09:56 UTC
Labels: enhancement
