### ISSUE TITLE
Music Quality

### ISSUE THREAD

**Issue by 3mnn** [vfsfitvnm/ViMusic#350] opened 2022-09-28 08:53 UTC
### Feature description

Everythings Great. But the music quality is kinda low. If you can at least give 256kbps it would be great.  Thanks for your kind work

### Why do you want this feature?

Can You Increase the music quality to 256kbps or higher?

**Comment by vfsfitvnm** [comment] 2022-09-28 08:57
Duplicate of #78

**Closed by vfsfitvnm** 2022-09-28 08:57 UTC
Labels: enhancement
