### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by Amitk003** [vfsfitvnm/ViMusic#1509] opened 2024-03-09 17:59 UTC
### Steps to reproduce the bug

"Even when I close and remove the app from the background, the music keeps playing."

### Expected behavior

When I close app from background, music should stoo

### Actual behavior

Yup, music should stop when I remove from background 

### ViMusic version

0.5.4

### Android version

Android 13

**Comment by sandraev** [comment] 2024-03-17 10:08
This is effectively not a bug, just a design choice. Please close this issue.

**Comment by Amitk003** [comment] 2024-03-17 10:11
Okay, isn't there any other way to do that

**Closed as completed** 2024-03-17 10:10 UTC
Labels: bug

**Comment by sandraev** [comment] 2024-03-17 10:20
Of course! You first have to pause the song currently playing and **then** close the app in the background.
It should work 😉

**Comment by Amitk003** [comment] 2024-03-17 10:21
Ok thanks 👍
