### ISSUE TITLE
Sync playlist updates

### ISSUE THREAD

**Issue by cslalexX** [vfsfitvnm/ViMusic#307] opened 2022-09-16 03:42 UTC
### Feature description

Sync changes in the YouTube Music official app or website to playlists of ViMusic after importing.

### Why do you want this feature?

It's easier to play someone's favorite music.

Thanks a lot.

**Comment by vfsfitvnm** [comment] 2022-09-16 14:43
Duplicate of #196

**Closed by vfsfitvnm** 2022-09-16 14:43 UTC
Labels: enhancement
