### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by k3rnelPan1c228** [vfsfitvnm/ViMusic#531] opened 2022-10-28 04:44 UTC
### Feature description

Can you make widget for this app please also thank you for making a wonderful app

### Why do you want this feature?

I usually have all my music stuff in the home screen for quick access, it also helps me to scroll through music and select a one specific song in a big playlist

**Comment by arfanmrafeek** [comment] 2022-10-28 04:56
Duplicate of #234 

@Bnyro , He may contribute but busy with vacation and he is now more centred towards his repo Libretube.

**Closed** 2022-10-28 05:28 UTC
Labels: duplicate, enhancement

**Comment by Bnyro** [comment] 2022-10-28 06:12
I wouldn't assign that to me at the moment, as for know I'm really just too busy with IRL stuff and maintaining LibreTube :/
