### ISSUE TITLE
Login & quality enhancement

### ISSUE THREAD

**Issue by Iam-mrinnocent** [vfsfitvnm/ViMusic#345] opened 2022-09-27 04:39 UTC
### Feature description

Add login option to protect playlist. And enhancement of audio quality for people like me who enjoys high quality music a lot.

### Why do you want this feature?

We will lost all playlist if we don't have login option & some people like to enjoy music at 320kbps

**Comment by vfsfitvnm** [comment] 2022-09-27 05:38
Duplicate of #208 and #78

**Closed by vfsfitvnm** 2022-09-27 05:38 UTC
Labels: enhancement
