### ISSUE TITLE
Music doesn't stop when app is conpletely closed

### ISSUE THREAD

**Issue by sebsebseb9b** [vfsfitvnm/ViMusic#305] opened 2022-09-15 21:25 UTC
### Steps to reproduce the bug

1. Play a song
2. Enable task changer
3. Quit vimusic
4. But the music keeps playing

### Expected behavior

It should stop playing music

### Actual behavior

It keeps playing

### ViMusic version

0.4.3

### Android version

12

**Comment by Malopieds** [comment] 2022-09-16 13:21
duplicate of #153

**Comment by sebsebseb9b** [comment] 2022-09-16 13:27
Are you going to fix it?

Also can you implement a way to disable recent song listened to from home page. And just show or hide stuff anything

**Comment by vfsfitvnm** [comment] 2022-09-16 14:42
Not a bug, this is just how a music player should work

**Closed by vfsfitvnm** 2022-09-16 14:42 UTC
Labels: bug

**Comment by sebsebseb9b** [comment] 2022-09-16 15:27
Literally every music player stops wjen you quit.. Every one.. You're the first i ever seen

**Comment by sebsebseb9b** [comment] 2022-09-16 15:28
It would be great if you could implement the option to do this.

**Comment by sebsebseb9b** [comment] 2022-09-16 15:28
Others have brought up this issue too. Im not the only one
