### ISSUE TITLE
Can't Reorder Playlists

### ISSUE THREAD

**Issue by Muteplayer** [vfsfitvnm/ViMusic#287] opened 2022-09-08 14:11 UTC
### Steps to reproduce the bug

Enter on saved playlist or create one
Add two or more songs
Try reorder

### Expected behavior

Save new order of playlist

### Actual behavior

Go back to old order

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/107940851/189144307-56690068-0b1f-4946-ae9c-df969508af17.mp4

### ViMusic version

0.4.3

### Android version

Android 12L (12.1)

**Comment by vfsfitvnm** [comment] 2022-09-09 06:06
@Muteplayer What about other playlists?

**Comment by vfsfitvnm** [comment] 2022-09-09 11:13
Thanks. Unfortunately I cannot reproduce.
Would you try the latest debug apk (https://github.com/vfsfitvnm/ViMusic/suites/8158854540/artifacts/354240072) and see if it works?

**Comment by vfsfitvnm** [comment] 2022-09-10 18:12
This is very odd to be honest. Just to make sure, would you share your database (Settings > Backup & Restore)?

**Comment by vfsfitvnm** [comment] 2022-09-15 17:50
Ok, I rewrote the query so it is a one-shot thing now. If it still doesn't work, I'll wait one week before closing this issue - it doesn't look like it's a problem I can solve.

Latest debug apk: https://github.com/vfsfitvnm/ViMusic/suites/8312723030/artifacts/364966363

**Comment by vfsfitvnm** [comment] 2022-09-24 10:50
Closing until someone else reports this issue.

**Closed by vfsfitvnm** 2022-09-24 10:50 UTC
Labels: bug, can't reproduce

**Comment by yonatan8070** [comment] 2023-05-13 05:45
I'm also having this issue (or a very similar one), I can drag songs around, but the moment I though another song the list resets, and the changes are never saved. Here's a video:

https://github.com/vfsfitvnm/ViMusic/assets/45665471/29e6dfbd-c19d-4b76-bffe-964ce8104b1d

I will try to build ViMusic myself and try to debug this later if I'll have the time
