### ISSUE TITLE
Does not cache thumbnails of some cached songs

### ISSUE THREAD

**Issue by tampos4** [vfsfitvnm/ViMusic#59] opened 2022-06-26 03:30 UTC
### Steps to reproduce the bug

1. Force stop the app
3. Open app without any network connection

### Expected behavior

It should cache thumbnails of all the cached songs

### Actual behavior

It does not cache thumbnails of some of the cached songs

### ViMusic version

0.1.7

### Android version

Android 11

**Comment by vfsfitvnm** [comment] 2022-06-26 08:42
I cannot reproduce. Moreover, the cache is entirely handled by Coil (a library) and not by me.
Would you attach a video or something?

**Comment by BluePixel4k** [comment] 2022-07-02 14:12
I have the same problem. 
I have completely disabled the internet permission of the app for this video. As you can see some thumbnails are not loading:

https://user-images.githubusercontent.com/77979781/177004195-ebff2e34-8639-4e64-913d-64bad10a41ba.mp4

**Comment by vfsfitvnm** [comment] 2022-07-02 14:20
I don't think I can do something about this (other than changing the image loading library)...

**Comment by Felixnightshade** [comment] 2022-07-19 19:37
I would guess the cause of the issue is that the image cache can fill up before the music cache - thus leading to songs with no thumbnail. Just spitballing here since I haven't looked at the actual implementation.

**Comment by vfsfitvnm** [comment] 2022-07-23 11:00
Closing as I cannot reproduce.

**Closed by vfsfitvnm** 2022-07-23 11:00 UTC
Labels: bug

**Comment by BluePixel4k** [comment] 2022-09-24 16:12
I know its a tiresome topic, but the bug don't go away. Also a new installation (but with database restore) didn't solves the problem. Its really frustrating. 😞

Is there anything I can do to find the bug? 

Here is another example, where no thumbnails are showing at all:
https://user-images.githubusercontent.com/77979781/192107782-676689ff-980b-4236-ad17-ea509ccf3c57.mp4
I hadn't used the app for about 1 day and opened it without internet access.

**Comment by vfsfitvnm** [comment] 2022-09-24 16:20
Would you try the latest debug apk? I changed the directory where images are cached (to the proper "cache" folder).
Out of curiosity, how much storage do you have left? Also, what's the space (and percentage) used by the image cache (_Settings > Cache_)?

**Comment by BluePixel4k** [comment] 2022-09-24 16:32
> Would you try the latest debug apk? I changed the directory where images are cached (to the proper "cache" folder).

Okay, I will try this out. 👍🏼 

> Out of curiosity, how much storage do you have left? Also, what's the space (and percentage) used by the image cache (Settings > Cache)?

I have 55GB free space (from 128GB) and this is how it looks in the app:
<img src="https://user-images.githubusercontent.com/77979781/192108767-ae2f82c4-8a9d-462f-8eaf-78113c83b765.png" width="300" />
So I don't think it's a space problem.

**Comment by vfsfitvnm** [comment] 2022-09-24 16:39
Yeah, it doesn't seem so.

> I hadn't used the app for about 1 day and opened it without internet access.

What happens if you re-open it after few minutes?

**Comment by BluePixel4k** [comment] 2022-09-24 19:11
> > I hadn't used the app for about 1 day and opened it without internet access.
> 
> What happens if you re-open it after few minutes?

As long as I don't have internet, nothing changes. I restarted the app several times, but the thumbnails were still not displayed.

> > Would you try the latest debug apk? I changed the directory where images are cached (to the proper "cache" folder).
>
> Okay, I will try this out. 👍🏼

Sadly, the bug is still present ([with this version CI #80](https://github.com/vfsfitvnm/ViMusic/actions/runs/3088742506)). 
Currently, not all thumbnails are gone, but some from the cached songs. Like in my first video in this issue.

What I directly recognized, that the small thumbnails only get cached, if I play music in this small mode.
<img src="https://user-images.githubusercontent.com/77979781/192114209-9d3d5e0e-b141-4ecc-a202-cd9148c29a13.png" width="300" />
(picture is with no internet access, its a "cached"/offline song)

---

For your information: the bug don't occur every time. Often only after some hours, if I didn't used the app. 
Its a bit strange. 😕

**Comment by BluePixel4k** [comment] 2022-10-01 09:43
An update: I did many test cases with three phones:
- Pixel 5 with A13 (GrapheneOS) (error occur already with A12.1) 
- OnePlus3 with A11 (LineageOS)
- OnePlus1 with A11 (LineageOS)

I installed on all devices the release and debug version (on the Pixel 5 in the main and work profile -> four times).
I tried different scenarios, with database restore, with a clean database, with activated settings in the app, with no changed setting (with the exception of "ignore battery optimizations" and "invincible service").
I cached over 30 songs in every app and blocked the internet access for each.

Now, after many days without internet access:
- Pixel 5 -> No big and small thumbnails are showing. On all versions. For some, however, the bug took a bit longer to occur.
- OnePlus3  -> All big thumbnails are showing. In the app with all activated settings, some small preview thumbnails aren't displayed. In the other app everything work fine (release version). 
- OnePlus1 -> All big thumbnails are showing. In both apps, some small preview thumbnails aren't displayed.

On all devices, I notice that not all small thumbnails are cached in the player section (as I had already mentioned a post before).
<img src="https://user-images.githubusercontent.com/77979781/192114209-9d3d5e0e-b141-4ecc-a202-cd9148c29a13.png" width="300" />

I have not been able to figure out what exactly is causing the bug. 😟 
Is there anything more I can do to find the cause?

BTW: can you please reopen the issue?

**Comment by tampos4** [comment] 2022-10-01 10:11
So, the bug is only with CalyxOS (me currently using ) and GrapheneOS.

**Comment by vfsfitvnm** [comment] 2022-10-01 10:50
For your interest, when a song is playing, it's not guaranteed both thumbnails will be cached. In fact, if you keep the app closed, none of them will be downloaded. Another example is if you skip through X songs when the expanded player is showing, the small thumbnails won't be downloaded (because they aren't displayed).

A good indicator which tells you whether the cache is working is the thumbnail displayed in the notification. Would you confirm it's always displayed?

**Comment by BluePixel4k** [comment] 2022-10-01 11:50
> A good indicator which tells you whether the cache is working is the thumbnail displayed in the notification. Would you confirm it's always displayed?

Yes, but only for my OnePlus1 and OnePlus3. For the Pixel 5, after some hours without internet access, they are gone too.

> For your interest, when a song is playing, it's not guaranteed both thumbnails will be cached. In fact, if you keep the app closed, none of them will be downloaded. Another example is if you skip through X songs when the expanded player is showing, the small thumbnails won't be downloaded (because they aren't displayed).

Okay, so this explains one of the bugs. 
But with the setting "Show song cover" on the lockscreen, the big thumbnail is always downloaded, right? 

These both small thumbnail are not the same und are each downloaded separately, or?
<img src="https://user-images.githubusercontent.com/77979781/193407879-afde05c7-ded6-4b9e-9cdf-af76da9c2317.png" width="300" />

**Comment by BluePixel4k** [comment] 2022-10-23 08:46
First of all, I testet the new versions with your modification "[.respectCacheHeaders(false)](https://github.com/vfsfitvnm/ViMusic/commit/cfe5dc965f4a4e997eea645cf03a57d22d3b0275)" and its look like the bug is finally disappeared. 😍🎊 @vfsfitvnm thx for you efforts. 😇 
Nevertheless I will observe it further on.

> No, "show song cover" just uses the bitmap I use in the notification already. The notification thumbnail has a fixed width of 256dp. For reference, the thumbnail in the image you just sent is 54dp. On the other hand, the size of the thumbnail that is shown in the expanded player screen has a variable size because it depends on the device width. So, for each song, 3 images are downloaded (actually there are 4, keep reading), and these 3 images aren't interchangeable at all because they would look like shit.

Thx for the explanation. 👍🏼
Could you please configure the app in this way, that always all needed thumbnails gets downloaded? Thus the songs are fully offline and not only the music files with a handful of thumbnails. 
I think this make the app even more smoother. Furthermore these thumbnails don't need much storage.

>> These both small thumbnail are not the same und are each downloaded separately, or?
> >
> Ohh, thanks for reminding me this one. They are downloaded separately, but they should be the same indeed.

No problem. 😃
