### ISSUE TITLE
Download the Music

### ISSUE THREAD

**Issue by hectorhack909** [vfsfitvnm/ViMusic#491] opened 2022-10-22 07:51 UTC
### Feature description

Downloading music from a single button would be amazing. There are not many apps that can download the songs fast. If you get it, I think more people will they would download this app, as a wonderful music player and song downloader.

### Why do you want this feature?

I want this function to have and download my favorite playlists and songs. There are not many apps that can download the songs fast. If you get it, I think more people will they would download this app, as a wonderful music player and song downloader.

**Comment by vfsfitvnm** [comment] 2022-10-22 07:51
Duplicate of #83

**Closed by vfsfitvnm** 2022-10-22 07:51 UTC
Labels: enhancement
