### ISSUE TITLE
Playlist issue

### ISSUE THREAD

**Issue by Pratyush102** [vfsfitvnm/ViMusic#87] opened 2022-07-06 19:15 UTC
I cant add more than 38 songs in a Playlist.

**Comment by Pratyush102** [comment] 2022-07-06 19:25
I've created a Playlist and when I added 38 songs after that whenever I'm trying to add another song to it then the song doesn't gets added in that Playlist

**Comment by vfsfitvnm** [comment] 2022-07-06 19:28
That's weird, I can't reproduce. Are you trying to add the same song twice?

**Comment by vfsfitvnm** [comment] 2022-07-06 19:30
Thanks for the video, what happens if you try to add another song?

**Comment by Pratyush102** [comment] 2022-07-06 22:18
No I am trying to add different song
But it isn't getting added in the playlist

**Comment by vfsfitvnm** [comment] 2022-07-06 22:41
Would you share your database? You can export it in Settings > Backup & Restore > Backup

**Comment by vfsfitvnm** [comment] 2022-07-13 21:18
Closing as no additional info was provided (can't reproduce)

**Closed by vfsfitvnm** 2022-07-13 21:18 UTC
