### ISSUE TITLE
Import playlist from other music app(s) 

### ISSUE THREAD

**Issue by MattWork13579** [vfsfitvnm/ViMusic#367] opened 2022-10-03 20:11 UTC
### Feature description

Add a way to import playlists from Spotify, YouTube Music, etc into this app.

Might make sense to be in the create playlist pop up, or in the import portion of the settings menu.

This could be a prompt asking for a url of the playlist. 

### Why do you want this feature?

This would allow users to migrate easily from these other apps to vimusic, as well as listen to other friends playlists. 

### Additional information

I don't know how easily this feature could be added so if this doesn't fit into a feature request or if it is not a reasonable ask please remove it if so.

**Comment by vfsfitvnm** [comment] 2022-10-04 05:31
Duplicate of #81. Also, you can already import youtube playlists

**Closed by vfsfitvnm** 2022-10-04 05:31 UTC
Labels: enhancement
