### ISSUE TITLE
App closing 

### ISSUE THREAD

**Issue by mohamed1434** [vfsfitvnm/ViMusic#948] opened 2023-01-30 02:42 UTC
### Steps to reproduce the bug

1. Go to any page where the settings icon is shown.
2. Press the settings icon.
3. Now go back by pressing the back icon.
4. Repeat step 2 and 3 very fast.

### Expected behavior

It should go to settings sections and back to the pages.

### Actual behavior

After pressing the settings icon and back icon repeatedly fast , the app closes itself.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/22354688/215376333-06de1eb8-a396-4885-861b-de985e3069d4.mp4

### ViMusic version

0.5.4

### Android version

Android 12

**Comment by Syntax-Err5** [comment] 2023-01-30 03:17
This seems to happen only when you press the back arrow and the settings icon takes its place on the new page. You only need to press it twice. This includes pages like one of your playlists or an artist page.

**Comment by vfsfitvnm** [comment] 2023-01-30 07:31
Duplicate of #517

**Closed by vfsfitvnm** 2023-01-30 07:31 UTC
Labels: bug
