### ISSUE TITLE
In-app update system

### ISSUE THREAD

**Issue by sfaresee** [vfsfitvnm/ViMusic#48] opened 2022-06-17 04:44 UTC
### Feature description

When new update gets uploaded, it gives a notification or direct download through the app. Also clicking the app version will check for update. When an update appears it says the changelog.

### Why do you want this feature?

It'll be very helpful as it's getting update quite frequent. So going through the github page for checking update is a bit inconvenient. 

### Additional information

A "skip this update" button will be nice as sometimes the change isn't required at that time. This button can be next to the update button. Example: cloudstream 3. 
![image](https://user-images.githubusercontent.com/57977673/174226846-3aa68779-4bdc-47df-a738-39e327d0c4d5.png)

**Comment by vfsfitvnm** [comment] 2022-06-17 07:53
Duplicate of #7

**Closed by vfsfitvnm** 2022-06-17 07:53 UTC
Labels: enhancement
