### ISSUE TITLE
Login with Google Account

### ISSUE THREAD

**Issue by paperparatha** [vfsfitvnm/ViMusic#573] opened 2022-11-03 12:40 UTC
### Feature description

The ability to login with google account and sync playlist, history and likes. Allowing google to track listening habits so it can make song recommendations.

### Why do you want this feature?

A big selling point of YouTube to me is the video and music recommendations. Having the option to login with a google account will help the algorithm to learn music listening habits and make recommendations.

I don't have GSF on my phone so can't use the official app and I would rather use an open source app anyway

**Comment by vfsfitvnm** [comment] 2022-11-03 12:47
Not planning to do so. Duplicate of #28

**Closed by vfsfitvnm** 2022-11-03 12:47 UTC
Labels: enhancement
