### ISSUE TITLE
Search suggestions not working 

### ISSUE THREAD

**Issue by mkkumawat29** [vfsfitvnm/ViMusic#618] opened 2022-11-11 16:37 UTC
### Feature description

In the first version there's search suggestions when you search any song..now it's not working please update this

### Why do you want this feature?

For better experience

**Comment by NeeRaj-2401** [comment] 2022-11-11 16:47
duplicate of #569 

@mkkumawat29 please research before raising any new issue
![image](https://user-images.githubusercontent.com/88180887/201389160-0438043b-5264-407b-91bb-94b243770967.png)

**Closed** 2022-11-11 17:15 UTC
Labels: duplicate, enhancement
