### ISSUE TITLE
App crash when a radio is started for a specific artist

### ISSUE THREAD

**Issue by Temechon** [vfsfitvnm/ViMusic#90] opened 2022-07-07 12:51 UTC
### Steps to reproduce the bug

1. For artist "Zaoui", on any song, click on "More of Zaoui"
2. Click on button "Start radio"
3. Crash

It doesn't seem to happen with another artist or another song... 

### Expected behavior

The app should not crash.

### Actual behavior

The app crash.

### ViMusic version

0.1.7

### Android version

Android 12

**Comment by vfsfitvnm** [comment] 2022-07-07 13:01
Thanks for reporting! I cannot reproduce in the `master` branch, so I guess this has been fixed in the meantime (it doesn't start the radio, but at least it doesn't crash).

In YTM ([here](https://music.youtube.com/channel/UCLmajYLanmfMV6tokXjDepA)) the radio starts but not from a Zaoui song, in fact there's no radio endpoint for that artist.

**Comment by vfsfitvnm** [comment] 2022-07-07 13:04
In this scenario, I can implement a fallback (like YTM does), so the radio starts anyways.

**Comment by vfsfitvnm** [comment] 2022-07-08 13:16
Fixed! Don't worry about the tip :)

**Closed by vfsfitvnm** 2022-07-08 13:16 UTC
Labels: bug
