### ISSUE TITLE
Add favorite (heart) icon to notification player

### ISSUE THREAD

**Issue by JFMugen** [vfsfitvnm/ViMusic#201] opened 2022-08-11 15:23 UTC
### Feature description

I think it would make the "favorite" feature a lot more easy to use while browsing other programs etc. 

### Why do you want this feature?

To make it easier to add a song to favorites. 

### Additional information

![image](https://user-images.githubusercontent.com/61559703/184169573-45d112d3-5611-40ec-a3a2-827e109c3b1e.png)

Please don't use my drawing :D

**Comment by vfsfitvnm** [comment] 2022-08-11 15:26
Duplicate of #131

**Closed by vfsfitvnm** 2022-08-11 15:26 UTC
Labels: enhancement

**Comment by JFMugen** [comment] 2022-08-11 15:30
> Duplicate of #131

I tried to find similar request first but looks like I missed, mb :)
