### ISSUE TITLE
Be able to rename the songs

### ISSUE THREAD

**Issue by palikcuiho** [vfsfitvnm/ViMusic#308] opened 2022-09-16 09:52 UTC
### Feature description

Hi, thanks for the great app!
It would be convenient to be able to rename the songs when the artist and the title are incorrectly guessed. Thanks! (sorry, English is not my first language) 

### Why do you want this feature?

The playlists would be clearer, and the function "more of Artist" could be better used. 

### Additional information

![Screenshot_2022-09-16-11-51-58-366_it vfsfitvnm vimusic](https://user-images.githubusercontent.com/58831429/190612146-b61f70fe-8350-4ecb-8ff9-f34dd0f862e4.jpg)

**Comment by vfsfitvnm** [comment] 2022-09-17 08:09
Duplicate of #41

**Closed by vfsfitvnm** 2022-09-17 08:09 UTC
Labels: enhancement
