### ISSUE TITLE
Fix Thumbnail Resolution 

### ISSUE THREAD

**Issue by PassionateG1t** [vfsfitvnm/ViMusic#46] opened 2022-06-16 07:34 UTC
### Steps to reproduce the bug

Use [third party music widget](https://play.google.com/store/apps/details?id=com.jb.widget.music) and link it with ViMusic

### Expected behavior

This widget has access to notifications in order to detect which song is being played and it downloads the thumbnail of the played song (refer to screenshots)

### Actual behavior

With ViMusic, and unlike other services (spotify, newpipe, VLC) the thumbnails are extremely blurry inside the widget. I would assume that the resolution of the thumbnails that are being downloaded is low. 

### Screenshots/Screen recordings

![Screenshot_20220616-094559_Nova7-01](https://user-images.githubusercontent.com/107609269/174016169-3b9d3f0e-ba97-4c14-a7c9-994a2612b3e0.jpeg)
![Screenshot_20220616-094655_Nova7-01](https://user-images.githubusercontent.com/107609269/174016194-80af57e8-0909-4169-91f2-896df2afa40f.jpeg)
![Screenshot_20220616-095636_Nova7-01](https://user-images.githubusercontent.com/107609269/174016200-a0afa43f-40da-4581-b1dd-14ef412d6e1e.jpeg)

1st pic: vimusic
2nd: spotify
3rd: newpipe

### ViMusic version

0.15

### Android version

11

### Additional information

Other than that, I'd like to thank you for your efforts. Although the app is still in early development, it has proven to be a formidable alternative client to the mainstream ones.

**Comment by vfsfitvnm** [comment] 2022-06-16 09:38
This happens because I set the thumbnail dimensions lazily - so the third party widget picks the default (unmodified) one, which has a low resolution.

I could pass a bigger notification, but it won't solve the problem:
What if the widget is bigger? How much big is enough? I'd have to pass a **very big** dimension by default which could possibly lead to a huge mobile data waste.

So it is unclear to me how should I solve this "problem" (I wouldn't call this a bug) properly.

Out of curiosity, why are you using that widget? What are its advantages if compared to the notification?

**Comment by vfsfitvnm** [comment] 2022-06-16 10:21
They render better because they have/set a higher resolution.

Regarding youtube, this is the default thumbnail:
https://lh3.googleusercontent.com/9yoMtTxzRn7iWolvpuCRwlocXFh9csKADOnTx1lulOSieP83aPTge-dpe25Kr4VBK6kIeN1YQ7yzD7D-=w60-h60-l90-rj

As you can see it's very small. 
But if you [change the url parameters](https://developers.google.com/people/image-sizing), you get a higher resolution image:
https://lh3.googleusercontent.com/9yoMtTxzRn7iWolvpuCRwlocXFh9csKADOnTx1lulOSieP83aPTge-dpe25Kr4VBK6kIeN1YQ7yzD7D-=w2048-h2048-l90-rj

The problem is I can't "guess" the correct url parameters a third party app will use - this is literally out of my control.

**Comment by vfsfitvnm** [comment] 2022-06-16 18:47
@PassionateG1t I might add a widget in a future, pixel-perfect thumbnails will be displayed

**Comment by vfsfitvnm** [comment] 2022-06-23 11:07
Closing - there's nothing I can do. However, I enhanced the thumbnail resolution in notifications, so there _may_ be an improvement

**Closed by vfsfitvnm** 2022-06-23 11:07 UTC
Labels: bug, wontfix
