### ISSUE TITLE
if these possible to add, please do

### ISSUE THREAD

**Issue by MrConqueror** [vfsfitvnm/ViMusic#132] opened 2022-07-25 06:18 UTC
### Feature description

Can you add something like these in Homepage?

In Search section put Genre, OPM (Original Pinoy Music) POP,  Rap/HipHop R&B, Christian, etc.

### Why do you want this feature?

So that it's easy to browse/discover songs

current homepage is boring

### Additional information

![Screenshot_2022-07-25-14-15-48-25](https://user-images.githubusercontent.com/102837820/180710832-2651dfcc-3735-4663-921c-2ce258e493c3.jpg)
![Screenshot_2022-07-25-14-16-10-14](https://user-images.githubusercontent.com/102837820/180710838-b55dc966-de32-4c31-b5ac-492129a9a9b5.jpg)

**Comment by MrConqueror** [comment] 2022-07-25 06:20
Pictures from https://ymusic.io/

**Comment by vfsfitvnm** [comment] 2022-07-25 08:21
Duplicate of #36

**Closed by vfsfitvnm** 2022-07-25 08:21 UTC
Labels: enhancement
