### ISSUE TITLE
Easily Enqueue / Play the Next Song

### ISSUE THREAD

**Issue by mfadam786** [vfsfitvnm/ViMusic#271] opened 2022-09-01 00:48 UTC
### Feature description

After searching for a song, rather than long pressing a song and then clicking the "Play Next" or "Enqueue" options, either swipe left or right on a song to do these options. I would suggest swiping right to add a song to the queue, aka play that song next in the existing queue, and swiping left to add it to the end of the existing queue using the Enqueue option. 

### Why do you want this feature?

Just ease of access pretty much. It would just make it way easier to add a song to play next or add it to the end of the existing queue.

This would be an amazing addition to the existing app, which by the way I think is so cool and clean 🔥

**Comment by vfsfitvnm** [comment] 2022-09-01 07:54
Duplicate of #143

**Closed by vfsfitvnm** 2022-09-01 07:54 UTC
Labels: enhancement
