### ISSUE TITLE
Cannot select a database to restore 

### ISSUE THREAD

**Issue by habnixzutun** [vfsfitvnm/ViMusic#549] opened 2022-10-29 19:06 UTC
### Steps to reproduce the bug

Go to in app settings
Go to Database
Go to Restore
Try to select a previously Backup (.db file)
All files are greyed out

### Expected behavior

When selecting a file, the restoring process of the database should start

### Actual behavior

I wasn't able to select a previously exported Backup

### Screenshots/Screen recordings

I'm sorry the screenshots are in german

On my phone:
https://user-images.githubusercontent.com/82294942/198848274-1afd0900-5473-4436-836a-da1f742dff77.mp4

![Screenshot_2022-10-29-20-56-09-678_com google android permissioncontroller](https://user-images.githubusercontent.com/82294942/198848297-b21ba5cf-46c2-43ba-b39d-252a7f90fa75.jpg)

On my Laptop:
![Screenshot 2022-10-29 205649](https://user-images.githubusercontent.com/82294942/198848429-e75b6f42-eba7-41d6-896e-aed04ce8f64f.png)

![Screenshot 2022-10-29 205806](https://user-images.githubusercontent.com/82294942/198848439-c218486a-e30d-4791-bacc-8d571c8f3de5.png)

### ViMusic version

0.5.3

### Android version

Android 12

### Additional information

Works neither on my Phone ( Xiaomi Mi 10T | Android 12 | MIUI 13) nor on my Laptop in Windows Subsystem for Android (Acer Nitro 5 | Android 12). The App doesn't have any rights to read files from the internal storage but I'm also not able to give the app access to them because the app never asked for it and therefore my system settings app doesn't let me change that.

I'm happy to help you fixing this bug and I'm sorry if it's just something that I'm doing wrong

**Comment by vfsfitvnm** [comment] 2022-10-29 19:09
Duplicate of #536

**Closed by vfsfitvnm** 2022-10-29 19:09 UTC
Labels: bug
