### ISSUE TITLE
Bottom bar

### ISSUE THREAD

**Issue by Sameky** [vfsfitvnm/ViMusic#422] opened 2022-10-13 14:02 UTC
### Feature description

The side bar looks tremendously terrible on taller displays, but it looks amazing in widescreen. There's a reason why most apps use a bottom bar instead of a side bar, it is better looking and it has better user experience. Bring the side bar to the bottom when in portrait mode, and keep it on the side when in widescreen mode.

### Why do you want this feature?

Better looks and usability

**Comment by vfsfitvnm** [comment] 2022-10-13 14:19
Duplicate of #390

**Closed by vfsfitvnm** 2022-10-13 14:19 UTC
Labels: enhancement
