### ISSUE TITLE
Audio Quality Selection Support

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#442] opened 2022-10-15 03:59 UTC
### Feature description

It would be a good addition to have a quality selection option in settings.

### Why do you want this feature?

It would help save data by setting the option to `low` who have limited data or slow internet connection.

And who don't have any such prob, can simply select the higher one.

So, that it gives users' the choice to choose what they want or need.

### Additional information

`z-huang/music` has implemented this.

Preview:
![Screenshot_20221015-092040](https://user-images.githubusercontent.com/87353286/195967804-06dae863-0ecc-4275-b9f3-5533ddaea2cc.png)

**Comment by vfsfitvnm** [comment] 2022-10-15 06:21
Duplicate of #20

**Closed by vfsfitvnm** 2022-10-15 06:21 UTC
Labels: enhancement
