### ISSUE TITLE
Option to set stream quality 

### ISSUE THREAD

**Issue by AndiLeni** [vfsfitvnm/ViMusic#494] opened 2022-10-22 14:53 UTC
### Feature description

I'd like to be able to make a decision about the stream quality. 

### Why do you want this feature?

In some locations where the mobile network is not stable or expensive it would be nice to reduce the kbps of the stream to save mobile data.

**Comment by vfsfitvnm** [comment] 2022-10-22 14:54
Duplicate of #60

**Closed by vfsfitvnm** 2022-10-22 14:54 UTC
Labels: enhancement
