### ISSUE TITLE
Sound Quality Setting and Information

### ISSUE THREAD

**Issue by Ledenav** [vfsfitvnm/ViMusic#405] opened 2022-10-11 08:27 UTC
### Feature description

How many kbit/s is the sound quality? This must be specified. Could you just tell? It should also be specified in the application. The lower the better for mobile It would be much better if we could choose with the setting.

### Why do you want this feature?

Required to use without thinking about mobile data usage.

### Additional information

Even if there is no setting, how many kbit/s should be specified.

**Comment by vfsfitvnm** [comment] 2022-10-11 08:33
Long press the thumbnail to show such info:
<img src="https://user-images.githubusercontent.com/46219656/195040069-60f178f7-6330-4882-abe1-5a9ee9a76fd7.jpg" width="30%"/>

Duplicate of #60

**Closed by vfsfitvnm** 2022-10-11 08:33 UTC
Labels: enhancement

**Comment by Ledenav** [comment] 2022-10-11 09:10
The sound quality is very high.  It will increase mobile data usage. For low data you should add lower audio quality option.
