### ISSUE TITLE
Download option

### ISSUE THREAD

**Issue by Challenger008** [vfsfitvnm/ViMusic#458] opened 2022-10-17 05:11 UTC
### Feature description

May you have to add the download option also.
It is reliable for those users who dont have that much of internet that they use in this app.
So that it can save the internet also.
Hope you take this seriously.
Well this is really a nice app without adds!!
I really liked this app.

### Why do you want this feature?

For saving the internet!!

### Additional information

![Screenshot_2022_1017_104049](https://user-images.githubusercontent.com/115943746/196094171-d19b60c0-fd65-4ebf-b60b-2d9eceeb94b5.jpg)

**Comment by vfsfitvnm** [comment] 2022-10-17 05:27
Duplicate of #83

**Closed by vfsfitvnm** 2022-10-17 05:27 UTC
Labels: enhancement
