### ISSUE TITLE
Add features to add proxy or suppor Piped

### ISSUE THREAD

**Issue by Phantom35935** [vfsfitvnm/ViMusic#437] opened 2022-10-14 21:20 UTC
Hy, Youtube music is only available in few countries. It is not available in my country so turn on the VPN and then turning it off is annoying. So it would be great if there will be option to add proxy or this app stream music from '' https://piped.kavin.rocks/'' it has youtube music in search filters. 

For example '' https://piped.kavin.rocks/results?search_query=Without+you+arman&filter=music_songs''

Anyway Only option for proxy will also be great.

**Comment by vfsfitvnm** [comment] 2022-10-15 06:17
Duplicate of #2

**Closed by vfsfitvnm** 2022-10-15 06:17 UTC
