### ISSUE TITLE
Download option for offline mode

### ISSUE THREAD

**Issue by FaNticDaedlYs** [vfsfitvnm/ViMusic#551] opened 2022-10-30 06:47 UTC
### Feature description

It will be nice if there is option for downloading the music...
Offline mode would be great if added...
Please provide us with a download music option if possible..

### Why do you want this feature?

We want this feature as we wanna hear Music when there is availability of network... So yea pls try introducing download option or offline mode

**Comment by vfsfitvnm** [comment] 2022-10-30 07:07
Duplicate of #83

**Closed by vfsfitvnm** 2022-10-30 07:07 UTC
Labels: enhancement
