### ISSUE TITLE
Similar songs aren't getting suggested after playing from search

### ISSUE THREAD

**Issue by sidsharths1245** [vfsfitvnm/ViMusic#191] opened 2022-08-10 15:17 UTC
### Steps to reproduce the bug

Go to search
Search for a song
Play the song
When you check the queue the suggested songs aren't there 

### Expected behavior

There should be "similar" or suggested songs in the queue

### Actual behavior

No songs in the queue, it was working before 

### Screenshots/Screen recordings

![Screenshot_20220810-204648](https://user-images.githubusercontent.com/64619769/183941802-e639e63a-c996-4d11-bda2-776d09d937a4.png)

### ViMusic version

0.3.0

### Android version

Android 13

**Comment by vfsfitvnm** [comment] 2022-08-10 15:54
Duplicate of #186

**Closed by vfsfitvnm** 2022-08-10 15:54 UTC
Labels: bug
