### ISSUE TITLE
Download Option 

### ISSUE THREAD

**Issue by denyo81** [vfsfitvnm/ViMusic#607] opened 2022-11-08 21:58 UTC
### Feature description

A possibility to download videos as Mp3 or AAC file to save on the respective device. 

### Why do you want this feature?

This feature would be useful for saving and moving the downloaded songs to Mp3 players. So you have everything in one app.

**Comment by vfsfitvnm** [comment] 2022-11-09 06:19
Duplicate of #83

**Closed by vfsfitvnm** 2022-11-09 06:19 UTC
Labels: enhancement
