### ISSUE TITLE
Import spotify playlist

### ISSUE THREAD

**Issue by tjthejuggler** [vfsfitvnm/ViMusic#295] opened 2022-09-12 13:20 UTC
### Feature description

The ability to import a text playlist from another app, like spotify, into ViMusic.

### Why do you want this feature?

With Spotify you can export a playlist as a text file, it would make it much easier to leave spotify if this playlist could be imported into ViMusic.

**Comment by vfsfitvnm** [comment] 2022-09-12 13:22
Duplicate of #81

**Closed by vfsfitvnm** 2022-09-12 13:22 UTC
Labels: enhancement
