### ISSUE TITLE
Scrollable sidebar

### ISSUE THREAD

**Issue by Leonidios** [vfsfitvnm/ViMusic#632] opened 2022-11-13 14:51 UTC
### Feature description

The feature that I would like to see implemented is the ability of the user to scroll between the options of the sidebar. The switch between tabs would be triggered by the user scrolling on any part of the sidebar. 

### Why do you want this feature?

I believe that the sidebar the new update implemented makes use quite difficult because buttons are far to reach with the large screens that phones have these days. The ability to scroll between sidebar options would really make the use of the app easier.

**Comment by NeeRaj-2401** [comment] 2022-11-13 15:21
Track in #496

**Comment by vfsfitvnm** [comment] 2022-11-13 15:55
Duplicate of #398

**Closed by vfsfitvnm** 2022-11-13 15:55 UTC
Labels: enhancement
