### ISSUE TITLE
Feature 

### ISSUE THREAD

**Issue by Verandra** [vfsfitvnm/ViMusic#359] opened 2022-10-02 17:05 UTC
### Feature description

Would be good to could resgiter in the app and sinchronize in different devices to have same Playlist and favorites on all devices. 

### Why do you want this feature?

Better use... 🙂

**Comment by vfsfitvnm** [comment] 2022-10-02 17:18
Duplicate of #211

**Closed by vfsfitvnm** 2022-10-02 17:18 UTC
Labels: enhancement
