### ISSUE TITLE
offline play

### ISSUE THREAD

**Issue by suva-github-625466** [vfsfitvnm/ViMusic#335] opened 2022-09-24 13:14 UTC
### Feature description

  1. If the songs which are being played by this app can be downloaded then it will be very helpfool.
  2. And if we can play downloaded songs using vimusic then it will be very useful.

### Why do you want this feature?

i want song download feature because this is a competitor of YouTube music.
I want downloaded audio file play because i love this app and want my favourite features on this app.

### Additional information

OFFLINE AUDIO FILES PLAY :
![Screenshot_20220924-183952_1](https://user-images.githubusercontent.com/85799578/192099875-3eb6786b-077b-417d-8540-c8eb11b0d8a0.jpg)

SONG DOWNLOAD OPTION :
![Screenshot_20220924-183742_1](https://user-images.githubusercontent.com/85799578/192099884-2beee1e9-7dc9-4a1e-ba39-316067f58a1f.jpg)

**Comment by vfsfitvnm** [comment] 2022-09-24 13:27
Duplicate of #83

**Closed by vfsfitvnm** 2022-09-24 13:27 UTC
Labels: enhancement
