### ISSUE TITLE
On board music player along side with online 

### ISSUE THREAD

**Issue by RTE85** [vfsfitvnm/ViMusic#327] opened 2022-09-20 19:31 UTC
### Feature description

Please add a feature where the music player can read the on board already downloaded music so you can creat a play list with both online and already downloaded music.

### Why do you want this feature?

It would make things easier rather than looking for the already downloaded music and then playing it.

**Comment by vfsfitvnm** [comment] 2022-09-20 19:37
Duplicate of #57

**Closed by vfsfitvnm** 2022-09-20 19:37 UTC
Labels: enhancement
