### ISSUE TITLE
Update releated issue

### ISSUE THREAD

**Issue by luffy009-b** [vfsfitvnm/ViMusic#184] opened 2022-08-08 14:15 UTC
### Feature description

It would be great if you could add in-app update feature and new version update notification

### Why do you want this feature?

It is hassle sometimes to visit github to see if there's new update. It would save some time if you could just add this feature. Thanks

**Comment by vfsfitvnm** [comment] 2022-08-08 14:16
Duplicate of #48, #7

**Closed by vfsfitvnm** 2022-08-08 14:16 UTC
Labels: enhancement
