### ISSUE TITLE
Home and explore section like beatbump.ml

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#45] opened 2022-06-15 18:45 UTC
### Feature description

Just want a home and explore tab in this app like the beatbump project.

### Why do you want this feature?

This feature makes an music app more convenient. We will be able to see more songs options as we open the app.
Rather than going and searching something..

### Additional information

I just loved your work and efforts man  🙌 Even this is  my daily driver app now.

**Comment by vfsfitvnm** [comment] 2022-06-15 19:18
Thanks :)

Duplicate of #36!

**Closed by vfsfitvnm** 2022-06-15 19:18 UTC
Labels: enhancement
