### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by sahilahuja1729** [vfsfitvnm/ViMusic#326] opened 2022-09-20 14:45 UTC
### Feature description

A widget like media player notification like in A12 or A13 would be nice

### Why do you want this feature?

It would look cool on screen, easier to play songs directly from the widget.

### Additional information

please

**Comment by Malopieds** [comment] 2022-09-20 14:49
Duplicate of [#233](https://github.com/vfsfitvnm/ViMusic/issues/234)

**Closed** 2022-09-20 14:50 UTC
Labels: enhancement
