### ISSUE TITLE
locale ?

### ISSUE THREAD

**Issue by bristow** [vfsfitvnm/ViMusic#378] opened 2022-10-07 20:19 UTC
### Feature description

Vimusic in french, spanish, dutch and many more 🙂

### Why do you want this feature?

Because, all people don't speak english

### Additional information

Thanks for your amazing app !

**Comment by vfsfitvnm** [comment] 2022-10-08 05:08
Duplicate of #100

**Closed by vfsfitvnm** 2022-10-08 05:08 UTC
Labels: enhancement
