### ISSUE TITLE
Widgets 

### ISSUE THREAD

**Issue by Saks-16** [vfsfitvnm/ViMusic#429] opened 2022-10-14 01:00 UTC
### Feature description

This app should have widget of 5 x 1. Like we can put it on our home screen.

### Why do you want this feature?

I use mostly widgets than apps icon to open an app. 
This is why I want this feature to be added.

**Comment by vfsfitvnm** [comment] 2022-10-14 05:01
Duplicate of #234

**Closed by vfsfitvnm** 2022-10-14 05:01 UTC
Labels: enhancement
