### ISSUE TITLE
Not working in Samsung S22 Ultra

### ISSUE THREAD

**Issue by sudhanshu-malla** [vfsfitvnm/ViMusic#482] opened 2022-10-21 02:08 UTC
### Steps to reproduce the bug

Installed the app from f droid and github as well but both results in none of the feature working expect overview of artists. Search does not work as well. 

In other sections, like songs, the windows keeps on loading but won't show anything
 

### Expected behavior

For the app to work and show songs and play 

### Actual behavior

Just keeps on loading and won't work
 

### ViMusic version

0.5.1

### Android version

Android 12 , one uI 4.1

**Comment by vfsfitvnm** [comment] 2022-10-21 05:22
Duplicate of #480. Please update to 0.5.2

**Comment by vfsfitvnm** [comment] 2022-10-21 05:22
Alternatively, duplicate of #472

**Closed by vfsfitvnm** 2022-10-21 05:22 UTC
Labels: bug

**Comment by sudhanshu-malla** [comment] 2022-10-21 07:20
Installed 0.5.2 from github as not available from f droid but the issue still persists in s22 ultra

**Comment by Fatcakes** [comment] 2022-10-21 07:27
Read the actual post. Youtube music is not available in every country.

**Comment by sudhanshu-malla** [comment] 2022-10-21 07:28
UK being one of them?

**Comment by vfsfitvnm** [comment] 2022-10-21 09:22
Would you provide a screen recording?
