### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by JeremyStarTM** [vfsfitvnm/ViMusic#193] opened 2022-08-11 03:59 UTC
### Feature description

I would love to see german texts in the music player.

### Why do you want this feature?

To see the german translation in ViMusic.

### Additional information

If you want (since I read all other feature requests regarding this) I can translate all texts into German within a day, since I see much potential in ViMusic and I like it much already (I'm using it since a hour or so!).

**Comment by Malopieds** [comment] 2022-08-11 07:09
Hi,

This is a [duplicate of](https://github.com/vfsfitvnm/ViMusic/issues/100) and explained [here](https://github.com/vfsfitvnm/ViMusic/pull/171#issuecomment-1206528846) why this feature is not planned for now !

**Closed** 2022-08-11 07:45 UTC
Labels: enhancement
