### ISSUE TITLE
Higher quality notification image for Android 13

### ISSUE THREAD

**Issue by rhynec** [vfsfitvnm/ViMusic#470] opened 2022-10-19 03:02 UTC
### Feature description

Currently, the app provides an image which is too small for the bigger image display used in Android 13's notification player. Thus, it ends up looking very low quality when blown up to its proper size.

### Why do you want this feature?

Quality of life improvement.

**Comment by vfsfitvnm** [comment] 2022-10-19 05:10
The image is high quality enough - it's A13 that handles media notification poorly. TL;DR you need to enable "Show song cover" in Settings > Appearance.
Duplicate of #267

**Closed by vfsfitvnm** 2022-10-19 05:10 UTC
Labels: enhancement
