### ISSUE TITLE
Another languages

### ISSUE THREAD

**Issue by Steffino02** [vfsfitvnm/ViMusic#544] opened 2022-10-29 15:21 UTC
### Feature description

Can you add another languages? For example Italian, German, Spanish. 

### Why do you want this feature?

I am italian

**Comment by Steffino02** [comment] 2022-10-29 15:23
I can help with the translation into Italian, as I am an Italian mother tongue speaker

**Comment by vfsfitvnm** [comment] 2022-10-29 15:24
Duplicate of #100

**Closed by vfsfitvnm** 2022-10-29 15:24 UTC
Labels: enhancement
