### ISSUE TITLE
Slide album art to change songs

### ISSUE THREAD

**Issue by INSIDIOUS2007** [vfsfitvnm/ViMusic#526] opened 2022-10-27 06:55 UTC
### Feature description

In this feature we can slide left or right on the album art to change songs either to play next song or previous song.

### Why do you want this feature?

It is easy to change songs just by sliding instead of always using toggle next button.

### Additional information

Plz mle its animation smooth.thnks

**Comment by vfsfitvnm** [comment] 2022-10-27 07:04
Duplicate of #250

**Closed by vfsfitvnm** 2022-10-27 07:04 UTC
Labels: enhancement
