### ISSUE TITLE
Importing playlist from spotify

### ISSUE THREAD

**Issue by 2011CS020179** [vfsfitvnm/ViMusic#591] opened 2022-11-06 01:11 UTC
### Feature description

I need to import my playlist from Spotify please add up this feature 

### Why do you want this feature?

To import my Spotify playlist to vi music

**Comment by NeeRaj-2401** [comment] 2022-11-06 06:06
duplicate of #81 , #295 .... u may close it

**Closed** 2022-11-06 06:29 UTC
Labels: enhancement
