### ISSUE TITLE
Last.fm

### ISSUE THREAD

**Issue by vileodias** [vfsfitvnm/ViMusic#498] opened 2022-10-23 10:05 UTC
### Feature description

This text was translated using Google Translate. I would like to ask for integration with Last.fm, through an existing application on the platform. This is already available on Spotify, for example, and is very useful..

### Why do you want this feature?

To scrooble directly from Vimusic

**Comment by arfanmrafeek** [comment] 2022-10-23 10:15
Duplicate of #138

**Closed** 2022-10-23 10:35 UTC
Labels: enhancement
