### ISSUE TITLE
Songs play without sound

### ISSUE THREAD

**Issue by astarq** [vfsfitvnm/ViMusic#385] opened 2022-10-09 11:08 UTC
### Steps to reproduce the bug

1. Go to an album, a playlist, or search for a track
2. Play all the tracks one by one

### Expected behavior

Tracks should play as normal.

### Actual behavior

At least one (but often as many as 5 or more) of the tracks will play without any audio.

For all of these songs which have no sound, when they are played the first time, the Stats page will show the following details:

Volume: 100%
Loudness: -9986.00 dB
Bitrate: 10 kbps
Size: 136 kB
Cached : 136 kB (100%)

A few, but not many, of these songs will have different details on the Stats for Nerds page, when they are played subsequently, e.g. the song Blues Run the Game: 

Volume: 100%
Loudness: 1.20 dB
Bitrate: 121 kbps
Size: 3.1 MB
Cached : 136 kB (4%)

In this case, it can be observed that the track seems to have downloaded correctly, yet the app seems to be playing only the tiny portion which was cached the first time.

### Screenshots/Screen recordings

<p align="center">
  <img src="https://user-images.githubusercontent.com/63871973/194753289-35c91e60-8eb9-44db-b128-2db20d594a1c.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753292-3a43b5a9-2a54-47f0-92d9-c1b4ecfbdfee.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753294-394153e1-7828-46e7-81e8-b35a6972cf69.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753301-098687b9-30c9-480b-81f5-8d6ea38e4230.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753306-e2174f79-b474-4472-abe4-60f7e9c20e39.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753311-80dc2833-1171-4fe2-9a4b-5f690638155d.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753314-0659625d-6172-49d4-aea8-c0c157ab1d15.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753319-86844252-d937-414d-afb9-fbbe2cbd599b.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753279-b2399ff1-3fc4-4853-944f-2220369b5331.png" width="19%" />
  <img src="https://user-images.githubusercontent.com/63871973/194753283-e415f380-6e5d-44fd-b2cb-6115ef9b5885.png" width="19%" />
</p>

### ViMusic version

0.5.0

### Android version

Android 12 & 13

### Additional information

1. This bug occurs consistently throughout all versions of ViMusic, and is still present in the current 0.5.0

2. It occurs when playing videos from Youtube and songs from YT Music

3. Things which I've tried to no avail:
- enabling and disabling Loudness Normalization
- clearing the data and cache of the app
- reinstalling the app
- enabling and disabling Skip slience
- enabling and disabling persistent queue
- using different versions of the app on both my Asus Zenfone 8 and Samsung Galaxy S8 Plus
- used the app on both Android 12 and 13

4. It occurs for me on most albums and playlists, but I'll leave some examples of Albums which suffer from it for convenience:
- 5/13 tracks play without sound: https://music.youtube.com/playlist?list=OLAK5uy_ls_fpUCmTPygRqiSfSSSlUBuUfDUgnrUQ
- 1/4: https://music.youtube.com/playlist?list=OLAK5uy_nU_V6QD005uV4ZN4t2F-ESP80H7cGofCw
- 7/10: https://music.youtube.com/playlist?list=OLAK5uy_laCXL6BeiaVfJYmFUOj3NWbLZyvkPn6Yw

**Comment by vfsfitvnm** [comment] 2022-10-09 11:19
Thank you, I will take a look asap.

**Comment by vfsfitvnm** [comment] 2022-10-09 11:28
Hm, I could play all the songs correctly. I think those songs are not available in your country. Do they appear in the search result (if so, do they have the same id]?

Where are you from? What happens when you try to play such songs from the official YouTube music client?

**Comment by astarq** [comment] 2022-10-09 11:59
Than you for for checking this out. 

Wow - that's so weird. This problem has happened to me seemingly randomly with various songs ever since I started using ViMusic a few monthes ago.

It won't be the songs are unavailable in my country, since I'm from the U.K. (the problem occurs with U.K. artists as well as others).
I just checked, and yeah, they all appear in the search result with the same id. They also don't play from directly searching for them.

All play fine in offical YT music. I also tried using https://github.com/z-huang/music for the sake of it, and the result is the same, all play normally.

**Comment by vfsfitvnm** [comment] 2022-10-09 12:12
Thanks for trying z-huang's music. You said you tried to clear the app data. However, did you restore the database after doing so? Would you try the [latest debug apk](https://github.com/vfsfitvnm/ViMusic/suites/8684396730/artifacts/391555840) and see if it works?

**Comment by vfsfitvnm** [comment] 2022-10-09 12:30
Possibly related: https://github.com/zerodytrash/YouTube-Internal-Clients/issues/3#issuecomment-1248922070

**Comment by astarq** [comment] 2022-10-09 12:30
No problem. I can confirm that I didn't restore the database, and unfortunately that debug apk still has the same problem

**Comment by vfsfitvnm** [comment] 2022-10-09 13:09
Would you try [this](https://github.com/vfsfitvnm/ViMusic/suites/8685903106/artifacts/391663881) one?

Delete the old debug apk first!

**Comment by astarq** [comment] 2022-10-09 13:24
Huh. With that apk, I get this problem with every song:
![Screenshot_20221009-142332_Debug](https://user-images.githubusercontent.com/63871973/194759366-1ae4b49c-c8c7-4330-a5d4-cbf36bb0de58.png)

**Comment by vfsfitvnm** [comment] 2022-10-09 13:33
Yup, it was to confirm [this](https://github.com/yt-dlp/yt-dlp/pull/4593) is the problem you are facing. z-huang's doesn't have this problem because it uses the `ANDROID_MUSIC` youtube client; but I do use the (problematic) `ANDROID` one. I think I can just use it too instead, as it requires less effort than implementing the proper solution!

**Comment by vfsfitvnm** [comment] 2022-10-09 13:47
[Here](https://github.com/vfsfitvnm/ViMusic/actions/runs/3214345105)'s the last shot before doing the change. Please wait for the build to finish.

Meanwhile, would you share your database (Settings > Database > Backup)? I need it so I can see how to remove the wrong stored data (i.e. 136kb size and so on)

**Comment by astarq** [comment] 2022-10-09 14:02
I'm well impressed at how fast you figured all that out! And it's great to hear that there's a solution, since your app really is fantastic and I don't want to use anything else after trying it. Thanks again.

I tried that debug build: it gives the same behaviour as the last debug one. 

Here's my database file: https://send.vis.ee/download/1878d3961102c5f9/#ZPBmb_clz1JQwcVOlhvjHw

**Comment by vfsfitvnm** [comment] 2022-10-09 14:55
Whops, the issue was already fixed by the first commit. I forgot to add a thing (in fact now it throws that error in every song lol). It should work now

**Comment by astarq** [comment] 2022-10-09 15:49
Haha. It does work better, now, although now I get the error in the below screenshot, instead. A workaround for this seems to be to exit the app, force stop it, then go back and play the song again. That didn't work before, but does now. 
![Screenshot_20221009-164308_Debug](https://user-images.githubusercontent.com/63871973/194766484-4c610a73-9aea-4f39-b7b0-4215b8604a05.png)

**Comment by vfsfitvnm** [comment] 2022-10-09 16:26
It looks like a different problem - can you reproduce it? And what do you mean by "better"? Regarding the original one, do you think it is solved?

**Comment by astarq** [comment] 2022-10-09 17:32
Oops, sorry, should've mentioned that it happens as much as the earlier problem and is reproducible. It seems to be an evolved version of the old bug, to me.
Better because at least there's a workaround.

**Comment by vfsfitvnm** [comment] 2022-10-10 10:51
I'm using a GB VPN and I can't reproduce the issue after the commits linked here - but I can reproduce the old one if I switch back to `v0.5.0`.

Since you can reproduce it, would you share the `logcat`? So I can see the `status` of the responses.

**Comment by astarq** [comment] 2022-10-10 15:39
[ Here you go](https://send.vis.ee/download/ffdb1ccd864ce428/#YoWX2vvvkrIUh_OfowAmww) 

I used [https://www.f-droid.org/en/packages/io.github.muntashirakon.AppManager/](App Manager)  to take a this log, is that ok?

**Comment by vfsfitvnm** [comment] 2022-10-10 15:45
> InvalidResponseCodeException: Response code: 403

So you got 403 forbidden error code. I guess I'll just use another client :/

**Comment by astarq** [comment] 2022-10-10 20:24
I see. Hopefully that isn't too much work.

**Comment by vfsfitvnm** [comment] 2022-10-11 10:22
Would you try the latest debug build now?

**Comment by astarq** [comment] 2022-10-11 12:19
It works! Woohoo!!!

**Comment by vfsfitvnm** [comment] 2022-10-11 12:24
Finally, lol! Thanks for your patience!

**Closed by vfsfitvnm** 2022-10-11 12:24 UTC
Labels: bug

**Comment by astarq** [comment] 2022-10-11 12:44
Thank you for all the work you do! 🙏

**Comment by vfsfitvnm** [comment] 2022-10-12 12:23
`v0.5.1` is out. Unfortunately, to "recover" the affected songs you already played, you need to "Hide" them first. You view the "Hide" menu entry in either the home screen "Songs" tab, the artist screen "Library" tab or the search screen "Library" tab

**Comment by astarq** [comment] 2022-10-12 13:59
Thanks for letting me/anyone else who had this problem know! Since I had the problem with a lot of songs, it was quicker to just clear the cache. That seemed to do the job. 

If anyone else who had this problem reads this, do note that clearing the cache will remove offline songs.
