### ISSUE TITLE
Download option

### ISSUE THREAD

**Issue by Hk-178** [vfsfitvnm/ViMusic#150] opened 2022-07-31 01:52 UTC
### Feature description

Add the option to download music to a user selected folder . the download can be as single music or a whole playlist 

### Why do you want this feature?

It is great to download and hear the music offline 🤷🏻‍♂️

### Additional information

.

**Comment by vfsfitvnm** [comment] 2022-07-31 07:31
You can already listen to music offline.
Duplicate of #83

**Closed by vfsfitvnm** 2022-07-31 07:31 UTC
Labels: enhancement
