### ISSUE TITLE
Gesture support

### ISSUE THREAD

**Issue by CSEU0978** [vfsfitvnm/ViMusic#535] opened 2022-10-28 14:56 UTC
### Feature description

Additional gesture support for navigation on the play screen and the song queue. Customizable personal gestures for removing songs from queue, swipe functionality to skip to next/previous track.

### Why do you want this feature?

Ease of access and better UI controls

### Additional information

Functionality akin to Spotify or SoundCloud

**Comment by vfsfitvnm** [comment] 2022-10-28 15:03
Duplicate of #250 and #143

**Closed by vfsfitvnm** 2022-10-28 15:03 UTC
Labels: enhancement
