### ISSUE TITLE
Song progression bar stuck

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#286] opened 2022-09-07 21:27 UTC
### Steps to reproduce the bug

1. Open app
2. Choose a song
3. Press lyrics

I don't know what else to say, it just happened.

### Expected behavior

What should happen is that the bar progresses parallel to the song. 

### Actual behavior

What happened was rhat the bar froze at 27 seconds and wouldn't move. Bar was stuck on that time for all songs no matter how I skipped back and forward. Otherwise, the songs play as they intend. Just that the bar is stuck.

### Screenshots/Screen recordings

![Screenshot_20220907-232203](https://user-images.githubusercontent.com/109493802/188984078-8c47fe07-df6e-4970-9cde-32304f17652b.jpg)
![Screenshot_20220907-232211](https://user-images.githubusercontent.com/109493802/188984081-59b0bd15-c508-4cd8-a9cb-4d6f45a01ae6.jpg)

### ViMusic version

0.4.3

### Android version

Android 12

**Comment by vfsfitvnm** [comment] 2022-09-08 05:47
I apologize but this bug is invalid as it isn't helpful at all.
Possibly, duplicate of #148

**Closed by vfsfitvnm** 2022-09-08 05:47 UTC
Labels: bug
