### ISSUE TITLE
Import Music from Spotify/ other services

### ISSUE THREAD

**Issue by THEVINDICATOR** [vfsfitvnm/ViMusic#554] opened 2022-10-30 22:44 UTC
### Feature description

Please could a feature to import playlists from Spotify be added or from other music streaming services.

### Why do you want this feature?

Makes the transition to ViMusic easier

**Comment by vfsfitvnm** [comment] 2022-10-31 05:19
Duplicate of #295

**Closed by vfsfitvnm** 2022-10-31 05:19 UTC
Labels: enhancement
