### ISSUE TITLE
repeating after finish play an album

### ISSUE THREAD

**Issue by kroolzero** [vfsfitvnm/ViMusic#484] opened 2022-10-21 08:39 UTC
### Steps to reproduce the bug

1. play any album or play the last track on an album

### Expected behavior

just should stop play anything. 

### Actual behavior

repeat the whole album. 

### ViMusic version

0.5.2

### Android version

android 11

**Comment by vfsfitvnm** [comment] 2022-10-21 09:23
Duplicate of #276

**Closed by vfsfitvnm** 2022-10-21 09:23 UTC
Labels: bug
