### ISSUE TITLE
iOS version release?

### ISSUE THREAD

**Issue by Dazmed707** [vfsfitvnm/ViMusic#604] opened 2022-11-08 10:51 UTC
### Feature description

Date for iOS version release? alternative yatte https://github.com/yattee/yattee for music alone.

### Why do you want this feature?

Alone for Music in iOS

**Comment by vfsfitvnm** [comment] 2022-11-08 11:02
Nope (duplicate of #476)

**Closed by vfsfitvnm** 2022-11-08 11:02 UTC
Labels: enhancement
