### ISSUE TITLE
Big song titles

### ISSUE THREAD

**Issue by rickdtc** [vfsfitvnm/ViMusic#602] opened 2022-11-08 07:41 UTC
### Feature description

I would like it if we were able to see the full song tilte instead oc them being cut off like this.
![Screenshot_20221108-130933](https://user-images.githubusercontent.com/74096544/200503058-f45229b5-f4eb-42fb-92fd-a67b7a5f0b2d.jpg)
![Screenshot_20221108-131010](https://user-images.githubusercontent.com/74096544/200503174-d1e56c5b-8dab-4121-84bb-66ee009a3f3e.jpg)
![Screenshot_20221108-131005](https://user-images.githubusercontent.com/74096544/200503185-697eef2f-5f9d-4f8c-8aee-9ef168e76409.jpg)

### Why do you want this feature?

Can't differentiate different versions of the song.

**Comment by vfsfitvnm** [comment] 2022-11-08 07:52
Duplicate of #278

**Closed by vfsfitvnm** 2022-11-08 07:52 UTC
Labels: enhancement
