### ISSUE TITLE
Please Download option

### ISSUE THREAD

**Issue by Indelibleimprint** [vfsfitvnm/ViMusic#548] opened 2022-10-29 18:25 UTC
### Feature description

Your project is amazing except that there's no download option. I have the cache size to unlimited but it will delete everything if its "Too Full" even favorite music. As people cant seem to get you onto the download train. I'm willing to pay you $50 to add this feature. I only listen to music offline and your app is the closest thing to perfection. Cache is just not as fluid as downloading. And I know lots of people have been asking for this. I'm just willing to pay to help out!😊

### Why do you want this feature?

I only play offline so if I have a cache that can randomly delete everything it's not ideal. 

I have a 256 GB sd Card and cant even use it. I'm tired of finding my music gone after a long day of work listening to music to get into my car and have nothing there afterwords (no data)

**Comment by Indelibleimprint** [comment] 2022-10-29 18:28
I have the chance size to unlimited but it doesn't seem to want to cooperate. 😅

**Comment by vfsfitvnm** [comment] 2022-10-29 18:28
Duplicate of #83 and #384.

If the cache is getting deleted, it means your internal storage is full (or so)

**Comment by Indelibleimprint** [comment] 2022-10-29 18:29
Good god man your difficult.

**Closed** 2022-10-29 18:29 UTC
Labels: duplicate, enhancement

**Comment by Indelibleimprint** [comment] 2022-10-29 18:30
Why are you holding back an something that soooo many people would appreciate? Cache isn't ideal.
