### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by imashar7** [vfsfitvnm/ViMusic#137] opened 2022-07-26 13:39 UTC
### Feature description

Please add proxy support so we can also use this application in the countries where YouTube music is not available.

### Why do you want this feature?

I live in Pakistan and here YouTube music is not available. So i have to use VPN when ever i want to listen music on Vimusic.
Please add a proxy Support so that i dont have to use VPN.
Thanks.

**Comment by vfsfitvnm** [comment] 2022-07-26 13:45
Duplicate of #2

**Closed by vfsfitvnm** 2022-07-26 13:45 UTC
Labels: enhancement
