### ISSUE TITLE
In-app update

### ISSUE THREAD

**Issue by fardeen619** [vfsfitvnm/ViMusic#195] opened 2022-08-11 07:57 UTC
### Feature description

Whenever a new update came we should get a in-app update dialog box so we know new update is available and download.

### Why do you want this feature?

It is easier otherwise we have to check daily github whether new update is available that's the reason many people still using old version :(

**Comment by vfsfitvnm** [comment] 2022-08-11 07:59
Duplicate of #7 (take a look at other duplicates also)

**Closed by vfsfitvnm** 2022-08-11 07:59 UTC
Labels: enhancement
