### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by senolfndk** [vfsfitvnm/ViMusic#3] opened 2022-06-05 14:29 UTC
🤔

https://user-images.githubusercontent.com/52818836/172055460-36d69aa7-5792-42d0-8d58-2c16c017b821.mp4

**Comment by vfsfitvnm** [comment] 2022-06-05 15:42
Could you visit https://music.youtube.com/? I think you live in a country where YTMusic is not available yet

**Comment by senolfndk** [comment] 2022-06-05 19:07
youtube music supports in my country

**Comment by senolfndk** [comment] 2022-06-05 19:09
![Ekran görüntüsü 2022-06-05 220848](https://user-images.githubusercontent.com/52818836/172066584-87774be7-0798-4931-90f3-24b2d3f6bd17.png)

**Comment by senolfndk** [comment] 2022-06-05 19:23
😒
![Screenshot_20220605-222034](https://user-images.githubusercontent.com/52818836/172067132-2d94310f-99c9-4c39-9f35-4989c4f9ea15.jpg)
![Screenshot_20220605-222048_Settings](https://user-images.githubusercontent.com/52818836/172067134-04a6389e-6616-4ad9-a89f-038821309ff1.jpg)

**Comment by vfsfitvnm** [comment] 2022-06-05 19:40
Uhm, this is weird! It looks like you are using a VPN, may it be the cause?

`ktor` throws that exception somehow (I catch it [here](https://github.com/vfsfitvnm/ViMusic/blob/master/youtube-music/src/main/kotlin/it/vfsfitvnm/youtubemusic/Extensions.kt#L27)), a quick google research wasn't helpful.

**Comment by senolfndk** [comment] 2022-06-05 19:59
no i am using adguard ad blocking i turned it off and it was fixed

**Comment by vfsfitvnm** [comment] 2022-06-05 20:17
Ok, closing!

**Closed by vfsfitvnm** 2022-06-05 20:17 UTC
Labels: invalid
