### ISSUE TITLE
Make vimusic available in the share menu

### ISSUE THREAD

**Issue by GET100PERCENT** [vfsfitvnm/ViMusic#553] opened 2022-10-30 13:49 UTC
### Feature description

<img src="https://user-images.githubusercontent.com/116144024/198881851-fc460416-e651-487f-9276-363054b5e579.jpg" width="20%"/>

### Why do you want this feature?

If this feature is implemented, people can share music links to YouTube music to play that song.

### Additional information

Such feature is already implemented in another app called "innertune". If this feature will be implemented on vimusic it will be very helpful.

**Comment by ARBoyGo** [comment] 2022-10-30 14:47
By now this is the most requested features.
I really need this. 

Duplicate of #433

**Comment by Iam-Eshwar** [comment] 2022-10-30 15:33
Make a telegram Discussion Group please.

**Comment by ARBoyGo** [comment] 2022-10-30 17:09
@Iam-Eshwar 

> Make a telegram Discussion Group please.
It's easy to discuss everything

The Dev can't do it, Let's make one with some admins. 

If you are interested let's together do it. And the app update, We'll notify those who don't use GitHub...

**Comment by Iam-Eshwar** [comment] 2022-10-30 17:12
> @Iam-Eshwar 
> 
> > Make a telegram Discussion Group please.
> It's easy to discuss everything
> 
> The Dev can't do it, Let's make one with some admins. 
> 
> If you are interested let's together do it. And the app update, We'll notify those who don't use GitHub...



Ok bro . I will make one and share here ☺️

**Comment by ARBoyGo** [comment] 2022-10-30 17:15
> Ok bro . I will make one and share here ☺️

Create new issue for it. Don't add features or bug just blank issue.

**Comment by ARBoyGo** [comment] 2022-10-30 17:20
If we find a new feature request, We'll write it in GitHub
Starting with feature request from a telegram user.......
And if we find duplicate feature request We'll share what the Dev said about it. Etc ...

**Comment by ARBoyGo** [comment] 2022-10-30 17:23
@Iam-Eshwar 

Please add rules okay?....

**Comment by Iam-Eshwar** [comment] 2022-10-30 17:25
> @Iam-Eshwar 
> 
> Please add rules okay?....

Yeah bro.
Give me ur telegram account link

**Comment by ARBoyGo** [comment] 2022-10-30 17:26
> Yeah bro. Give me ur telegram account link

@Armuslimakhi

**Comment by Iam-Eshwar** [comment] 2022-10-30 17:36
It's ViMusic official telegram discussion group..
t.me/ViMusic_Official

**Comment by vfsfitvnm** [comment] 2022-10-30 17:45
@Iam-Eshwar 
The group name should be "ViMusic Discussion" (or whatever, not just "ViMusic"), the tag should follow the group name.
So, please remove "official" from the tag, and state somewhere the group is a userbase-driven chat (as there's no official group). Also, make it clear the dev himself is not a member of that group.

**Comment by Iam-Eshwar** [comment] 2022-10-30 17:51
> @Iam-Eshwar 
> The group name should be "ViMusic Discussion" (or whatever, not just "ViMusic"), the tag should follow the group name.
> So, please remove "official" from the tag, and state somewhere the group is a userbase-driven chat (as there's no official group). Also, make it clear the dev himself is not a member of that group.

Ok bro done already and tq so much

**Comment by Iam-Eshwar** [comment] 2022-10-30 17:52
> > @Iam-Eshwar 
> > The group name should be "ViMusic Discussion" (or whatever, not just "ViMusic"), the tag should follow the group name.
> > So, please remove "official" from the tag, and state somewhere the group is a userbase-driven chat (as there's no official group). Also, make it clear the dev himself is not a member of that group.
> 
> Ok bro done already and tq so much 

Please keep in touch bro ,in the telegram..

**Comment by Iam-Eshwar** [comment] 2022-10-30 18:04
It's ViMusic  telegram discussion group..
https://t.me/ViMusic_Repo

**Comment by ARBoyGo** [comment] 2022-10-30 18:45
@vfsfitvnm, I'm sorry this guy seem more like kid, I'm staying out of it. He/she doesn't seem to know Foss world and it's community based... 
I think I'll die teaching him 🤣 big mistake in my life 🤦. 
I told him to write fresh issue, Hope he do it, Rather than spamming. Hopefully 🤦.

**Comment by vfsfitvnm** [comment] 2022-10-31 12:23
@GET100PERCENT 
I apologize for the spam.

Regarding this issue, I won't implement it. ViMusic is already capable of opening youtube links. This is a different thing, however.

The "Share" intent is meant to share contents such as texts or images, <ins>not to handle urls</ins>. I don't want to include this bad habit in my app.

Moreover, the use case is rather obscure:

> If this feature is implemented, people can share music links to YouTube music to play that song.

Why would you need to do so? Why would you use another music client and then decide to forward the playback to vimusic?

**Closed by vfsfitvnm** 2022-10-31 12:23 UTC
Labels: enhancement

**Comment by GET100PERCENT** [comment] 2022-10-31 12:39
Okay, this was not an essential feature as I can make vimusic as the default app for opening YouTube music links.
But i have a question "Does vimusic uses newpipe extractor ?"

**Comment by vfsfitvnm** [comment] 2022-10-31 12:41
> Does vimusic uses newpipe extractor ?

Nope, it uses its own library

**Comment by ARBoyGo** [comment] 2022-10-31 16:58
Please hide the off-topic
