### ISSUE TITLE
App crashes when I try to close it from notification bar

### ISSUE THREAD

**Issue by snoopy112** [vfsfitvnm/ViMusic#366] opened 2022-10-03 19:31 UTC
### Steps to reproduce the bug

1. Open ViMusic and start to play music from Offline folder (doesn't reproduce from Favorites)
2. Change player and start playing music
3. Open notification panel and swipe ViMusic player to left to close app

### Expected behavior

Normal exit behaviour

### Actual behavior

App crashes

### Logs

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.vfsfitvnm.vimusic, PID: 10171
    java.lang.IllegalStateException
        at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
        at androidx.media3.datasource.cache.SimpleCache.isCached(SimpleCache.java:494)
        at it.vfsfitvnm.vimusic.ui.screens.BuiltInPlaylistScreenKt$BuiltInPlaylistScreen$1$invoke$lambda-5$lambda-3$$inlined$map$1$2.emit(Emitters.kt:228)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

### ViMusic version

0.4.3

### Android version

Android 8.1 & 9

**Comment by vfsfitvnm** [comment] 2022-10-03 19:36
Thanks, I could reproduce :)
It happens because it tries to read the cache database after being released

**Comment by snoopy112** [comment] 2022-10-03 19:40
It seems problem in BuiltInPlaylistScreen.kt (74 line BuiltInPlaylist.Offline -> Database.songsWithContentLength().map ...)

**Comment by vfsfitvnm** [comment] 2022-10-03 20:01
This is somehow already fixed in the `redesign` branch (which will be merged with `master` in a week or so)!

**Closed by vfsfitvnm** 2022-10-03 20:01 UTC
Labels: bug
