### ISSUE TITLE
Play Local Files

### ISSUE THREAD

**Issue by GasparGT11** [vfsfitvnm/ViMusic#595] opened 2022-11-06 15:02 UTC
### Feature description

I want to play the music stored in my device, with an option to add them to my playlists.

### Why do you want this feature?

I have a "couple" of songs uploaded to YTM. But since only I can see them in my account, it can't be played on ViMusic. In that case I will play them locally, just like in Spotify.

**Comment by vfsfitvnm** [comment] 2022-11-06 15:32
Duplicate of #57!

**Closed by vfsfitvnm** 2022-11-06 15:32 UTC
Labels: enhancement
