### ISSUE TITLE
Vimusic doesn't work 

### ISSUE THREAD

**Issue by Chriis-MarTin** [vfsfitvnm/ViMusic#342] opened 2022-09-25 12:18 UTC
### Steps to reproduce the bug

Go to the app and search any song, or album

### Expected behavior

The song or album should come up.

### Actual behavior

But the app said: no result found, please try a different query or category.

### Screenshots/Screen recordings

![Uploading Screenshot_20220925-185334.png…]()
![Screenshot_20220925-185239](https://user-images.githubusercontent.com/86178281/192142421-fcc106ff-28fd-4a42-a70c-6f4c47af70cb.png)
![Screenshot_20220925-185347](https://user-images.githubusercontent.com/86178281/192142424-dc40453e-0613-4b64-b110-6d67411ddeab.png)

### ViMusic version

0.4.3

### Android version

Android 10 go

**Comment by vfsfitvnm** [comment] 2022-09-25 12:42
Duplicate of #325

**Closed by vfsfitvnm** 2022-09-25 12:42 UTC
Labels: bug
