### ISSUE TITLE
Show top bar while scrolling up

### ISSUE THREAD

**Issue by dhishkyaon** [vfsfitvnm/ViMusic#198] opened 2022-08-11 12:28 UTC
Please add option to automatically show top bar while scrolling upwards. something like this

https://user-images.githubusercontent.com/88529066/184133214-5ce3cc8d-a48f-4560-b270-ff9562746742.mp4

**Comment by vfsfitvnm** [comment] 2022-08-11 12:36
Duplicate of #169

**Closed by vfsfitvnm** 2022-08-11 12:36 UTC
