### ISSUE TITLE
Widgets for homescreen

### ISSUE THREAD

**Issue by MillionsToOne** [vfsfitvnm/ViMusic#559] opened 2022-10-31 10:49 UTC
### Feature description

A widget for Vimusic that you could use to skip, pause and go back

### Why do you want this feature?

Because I am lazy as f and you wouldn't need to drag quick settings to skip track etc

**Comment by ARBoyGo** [comment] 2022-10-31 10:51
Duplicate of #234

**Closed** 2022-10-31 11:05 UTC
Labels: enhancement
