### ISSUE TITLE
Sponsorblock

### ISSUE THREAD

**Issue by tampos4** [vfsfitvnm/ViMusic#223] opened 2022-08-17 17:51 UTC
Please implement [Sponsorblock](https://sponsor.ajay.app/) just like [NewPipe x SponsorBlock](https://github.com/polymorphicshade/NewPipe).

At least these categories -

* Music : Non-Music Section
* Intermission / Intro Animation
* Endcards /Credits

**Comment by vfsfitvnm** [comment] 2022-08-17 17:59
Duplicate of #160

**Closed by vfsfitvnm** 2022-08-17 17:59 UTC
