### ISSUE TITLE
Offline playlists?

### ISSUE THREAD

**Issue by thesupertechno** [vfsfitvnm/ViMusic#564] opened 2022-11-01 13:15 UTC
### Feature description

The ability to download your playlists to play offline

### Why do you want this feature?

Main reason is for offline music. I don't have internet all the time, and it would be nice to be able to download and play my playlists I create on here wherever and whenever, internet or not.

**Comment by vfsfitvnm** [comment] 2022-11-01 13:23
Duplicate of #83

**Closed by vfsfitvnm** 2022-11-01 13:23 UTC
Labels: enhancement
