### ISSUE TITLE
Download button .

### ISSUE THREAD

**Issue by Rohan45548** [vfsfitvnm/ViMusic#297] opened 2022-09-13 13:05 UTC
### Feature description

Download button to download the songs in app and the songs which I downloaded should save in the app not in my phone.

### Why do you want this feature?

I like to listen the songs in offline mode and it will help the when I don't have internet to listen the songs, so it my request please add the download button to app .
I have found this app in this week and l like the UI of app and it is  adds free .

**Comment by vfsfitvnm** [comment] 2022-09-13 13:23
Duplicate of #83

**Closed by vfsfitvnm** 2022-09-13 13:23 UTC
Labels: enhancement
