### ISSUE TITLE
Active vs Passive Offline Download 

### ISSUE THREAD

**Issue by okidoki-jpg** [vfsfitvnm/ViMusic#426] opened 2022-10-13 19:34 UTC
### Feature description

initiate offline download instead of passive download 

### Why do you want this feature?

it'd be great if i could initiate an offline download rather than have to play an entire song or album before the songs become available offline.

**Comment by vfsfitvnm** [comment] 2022-10-13 19:36
Duplicate of #83

**Closed by vfsfitvnm** 2022-10-13 19:36 UTC
Labels: enhancement
