### ISSUE TITLE
Notification pause play not working

### ISSUE THREAD

**Issue by marcecfilip** [vfsfitvnm/ViMusic#255] opened 2022-08-26 22:44 UTC
### Steps to reproduce the bug

1. Play any song then pause
2. Go out of the app without clearing it
3. Try playing again from the notification
4. Song does not play

Or 
1. Play any song then pause from noification
2. Try playing again
3. Song does not play

### Expected behavior

Song should start playing again

### Actual behavior

Song does not play

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/111235216/186999738-e3dc7237-d9ae-4141-93a6-3003a2f5082a.mp4

### ViMusic version

0.4.2

### Android version

Android 12

**Comment by sandraev** [comment] 2022-08-27 08:53
Weird... I does not affect my phone... I have the same Android version and the same ViMusic.

**Comment by sandraev** [comment] 2022-08-27 08:56
Maybe it's due to a custom UI from your phone's vendor ? MIUI ? OneUi ?
Actually, I have the LineageOS one (AOSP).

**Comment by vfsfitvnm** [comment] 2022-08-27 09:18
Same as #202 , I cannot reproduce on the A12 emulator.

**Comment by marcecfilip** [comment] 2022-08-27 14:08
> Maybe it's due to a custom UI from your phone's vendor ? MIUI ? OneUi ?
> Actually, I have the LineageOS one (AOSP).

Probably beacuse it doesn't work on my other phone either also running Andorid 12 and OneUi 4.1

**Comment by vfsfitvnm** [comment] 2022-08-27 19:27
I got my hands on a one ui 4.1 a12 device! I'm going to see if I can reproduce and provide the fix tomorrow

**Comment by vfsfitvnm** [comment] 2022-08-28 09:39
I cannot reproduce:

https://user-images.githubusercontent.com/46219656/187067490-70ff15cc-0ba4-4736-8420-8483395ecd66.mp4

I'm going to close this one as I assume this is a device or system image specific issue - unless you provide more details so I can understand where the problem is.

**Comment by marcecfilip** [comment] 2022-08-30 19:12
It started working fine again even though I haven't changed anything i don't know what to say.

**Closed** 2022-08-30 19:36 UTC
Labels: bug, can't reproduce
