### ISSUE TITLE
Download music 

### ISSUE THREAD

**Issue by Kr1shtan** [vfsfitvnm/ViMusic#490] opened 2022-10-22 06:57 UTC
### Feature description

I'm more than sure that I'm not the first person to write this to you, but... In ViMusic, I would like to see the ability to download music (audio clips). Everything is fine in this application: design, intuitive interface. The very ability to listen to YouTube and YouTube Music in a separate application, without ads - it's great! But there is simply not enough opportunity to download music, and not just save it in the cache

### Why do you want this feature?

Just imagine. A person does not have mobile Internet at all, but he wants to listen to music or podcasts on YouTube, for example, on the train to school or to work. Of course, he can find some site, download mp4 from it (if it's a podcast), find another site, convert it to mp3, delete mp4, which can weigh very little. And so many actions are tedious to perform to save a YouTube video to your phone so you can just listen to it. But if ViMusic had the ability to actually download audio clips, and not just save them in the cache, it would make people's lives easier and more comfortable.

### Additional information

Is it difficult to add a download button, for example, under the "Like" button..? In the settings, you can select the root folder where everything will be uploaded. 

That would be nice...

**Comment by vfsfitvnm** [comment] 2022-10-22 07:29
Duplicate of #83.
I'm not planning to a "download to external storage" right now, but read the discussion.

**Closed by vfsfitvnm** 2022-10-22 07:29 UTC
Labels: enhancement
