### ISSUE TITLE
Audio quality

### ISSUE THREAD

**Issue by sn4k326** [vfsfitvnm/ViMusic#567] opened 2022-11-02 16:52 UTC
### Feature description

Show the audio quality/bitrate and give the possibility ti change it

### Why do you want this feature?

Ti know the quality of the music i'm listening

**Comment by vfsfitvnm** [comment] 2022-11-02 16:57
Duplicate of #60. Also, long press the song cover to show the stats for nerds

**Closed by vfsfitvnm** 2022-11-02 16:57 UTC
Labels: enhancement
