### ISSUE TITLE
How should I add songs to the offline playlist?

### ISSUE THREAD

**Issue by Nobody1323** [vfsfitvnm/ViMusic#362] opened 2022-10-03 05:35 UTC
### Steps to reproduce the bug

Searched for a song
Clicked on its three dots for additional options
Didn't see any feature to add the song to offline mode
Added it to favorites hoping it would work.
Still it didn't 

### Expected behavior

A facility to have online songs offline

### Actual behavior

Nothing worked

### ViMusic version

0.4.3

### Android version

Android 12

**Comment by NR8124** [comment] 2022-10-03 06:13
played songs are cached automatically. u can find them in offline section.

**Comment by vfsfitvnm** [comment] 2022-10-03 08:12
Duplicate of #83

**Closed by vfsfitvnm** 2022-10-03 08:12 UTC
Labels: bug
