### ISSUE TITLE
Add download switcher in playlist page

### ISSUE THREAD

**Issue by qolbudr** [vfsfitvnm/ViMusic#178] opened 2022-08-07 08:54 UTC
### Feature description

Add download switch that download all collected song in a playlist

![IMG_20220807_154855](https://user-images.githubusercontent.com/61232165/183282973-523ff15f-5bf5-4ecb-baf2-f846ab4a35ae.jpg)

but you know the row that have download text and switcher beetween  title and shuffle button

### Why do you want this feature?

Download song feature currently using cached strategy, the main problem is if i wanna download many songs in my playlist i should listen to all songs until finished and then the song getting cached it took couple times.

**Comment by vfsfitvnm** [comment] 2022-08-07 08:59
Duplicate of #83 

However, you don't need to fully listen to a song in order to cache it. Here's a little trick to cache a song in a couple of seconds:

https://user-images.githubusercontent.com/46219656/183283360-0f851f58-70b5-4aff-9af4-86c2f3f9dfda.mp4

**Closed by vfsfitvnm** 2022-08-07 08:59 UTC
Labels: enhancement

**Comment by qolbudr** [comment] 2022-08-07 09:10
so i need to open all song in my playlist one by one ?

it really easy to have switcher and all song in my playlist started to download

**Comment by vfsfitvnm** [comment] 2022-08-07 09:16
Yes, I know it is easier - but this what you can do now.
Why do you want to pre-cache all those songs? All I can think of is you need to go somewhere where you don't have internet access and you want to listen to songs you never listened to before. Is that correct?

**Comment by qolbudr** [comment] 2022-08-07 09:27
No its not correct, i just want all of song in my playlist can played offline, and then if i add new song i want it automatically being downloaded

**Comment by vfsfitvnm** [comment] 2022-08-07 09:32
Then I don't think a download feature is needed if you don't have internet connection problems...

**Comment by qolbudr** [comment] 2022-08-07 09:36
some of people playing game with playing music, and if the music not downloaded before, it will broken connection while playing game,

i.e: lag, ping drop, etc.

**Comment by qolbudr** [comment] 2022-08-07 15:42
> All I can think of is you need to go somewhere where you don't have internet access and you want to listen to songs you never listened to before. Is that correct?

And it is true 🙁

**Comment by uGeek** [comment] 2022-08-10 22:30
In my case, if I have been in a place where there was no Internet, my connection was not fast enough and I have missed downloading the offline lists

**Comment by LikDev-256** [comment] 2022-10-12 10:33
Is it possible to implement a download system like,
[Music app](https://github.com/z-huang/music)
Bcz this application has a better UI and other many things better than the music project. And I don't like the material you UI

I would love to help the development in my free time but having a discord server for discussions is better.

**Comment by vfsfitvnm** [comment] 2022-10-12 10:48
@LikDev-256 see #83
