### ISSUE TITLE
the ability to add a playlist via a link

### ISSUE THREAD

**Issue by Wjxfi** [vfsfitvnm/ViMusic#407] opened 2022-10-11 11:03 UTC
### Feature description

I don't want to make the playlist public. I want to find the playlist through a private link. but this app doesn't search for the playlist. please add this feature

### Why do you want this feature?

I have 3,000 tracks in these playlists

### Additional information

newpipe already has this feature. but it's too bad for listening to music. so please add it here

I'm talking about youtube music

**Comment by vfsfitvnm** [comment] 2022-10-11 11:09
There's already. Search in other issues how to do that

**Comment by vfsfitvnm** [comment] 2022-10-11 11:10
Duplicate of #97

**Closed by vfsfitvnm** 2022-10-11 11:09 UTC
Labels: enhancement

**Comment by vfsfitvnm** [comment] 2022-10-11 12:23
No, you are the stupid one here. You said "private link": private means you (and you only) can access it (https://support.google.com/youtube/answer/3127309?hl=en) - you need an account to do that. 
You perhaps meant "unlisted link". And again, here's why you are even more stupid: you can already import a playlist by its link. You can't even read the README, you can't even read the issue template that tells you to search before posting and you didn't even try to see if the method the app you used to import playlists worked here as well (spoiler: it does).
