### ISSUE TITLE
Last.fm scrobbling

### ISSUE THREAD

**Issue by shie1** [vfsfitvnm/ViMusic#249] opened 2022-08-23 19:51 UTC
### Feature description

Users should be able to sign in with last.fm and scrobble their songs.

### Why do you want this feature?

I am a lastfm user, but ever since I switched im inactive on the site because, I cant scrobble my songs. I find the api easy to use and I think a lot of people would like this.

**Comment by vfsfitvnm** [comment] 2022-08-23 20:16
Duplicate of #138

**Closed by vfsfitvnm** 2022-08-23 20:16 UTC
Labels: enhancement
