### ISSUE TITLE
Vpn option 

### ISSUE THREAD

**Issue by abdelhak96** [vfsfitvnm/ViMusic#515] opened 2022-10-25 13:03 UTC
### Feature description

the ability to change the region inside the Vimusic app without the need of vpn.

### Why do you want this feature?

i use this app in an african region in algeria exactly, and the app doesn't work cause YouTube music is not supported here so in order to use the app i have to activate the vpn each time. 
so iam wondering if it's possible for you to change the region to usa and keep it as standard so everyone in the world can experience youtube ViMUSIC without the need of VPN.

**Comment by vfsfitvnm** [comment] 2022-10-25 13:08
> the ability to change the region inside the Vimusic app without the need of vpn.

This is just impossible. Duplicate of #2

**Closed by vfsfitvnm** 2022-10-25 13:08 UTC
Labels: enhancement
