### ISSUE TITLE
Home page loading issue

### ISSUE THREAD

**Issue by figo2001** [vfsfitvnm/ViMusic#451] opened 2022-10-16 06:12 UTC
![Screenshot_2022-10-16-11-39-47-385_it.vfsfitvnm.vimusic.jpg](https://user-images.githubusercontent.com/78696850/196021010-50f4718f-dc22-4dfe-99fe-391a22fea60d.jpg)

**Comment by figo2001** [comment] 2022-10-16 06:20
Can you please help me out of this bug? 
It still happens after I reinstalled the app and forced to stop option.

**Comment by vfsfitvnm** [comment] 2022-10-16 06:24
Duplicate of #414

**Closed by vfsfitvnm** 2022-10-16 06:24 UTC
