### ISSUE TITLE
Update from app

### ISSUE THREAD

**Issue by arijit4** [vfsfitvnm/ViMusic#389] opened 2022-10-09 16:35 UTC
### Feature description

There should be a butto to install latest version of the app. There may be another checkbox to make auto updates to the app.

### Why do you want this feature?

It's a kind of hassle to check for updates every now and then ans download every single releases.

**Comment by vfsfitvnm** [comment] 2022-10-09 16:40
Duplicate of #7

**Closed by vfsfitvnm** 2022-10-09 16:40 UTC
Labels: enhancement
