### ISSUE TITLE
The app crashes when the song info is displayed 

### ISSUE THREAD

**Issue by Gameronwork** [vfsfitvnm/ViMusic#1092] opened 2023-06-15 17:56 UTC
### Steps to reproduce the bug

1.open the app
2.play a song
3.long press the poster to view info of the song
And it crashes.

### Expected behavior

The app shouldn't crash and the info should be displayed properly 

### Actual behavior

The app crashes 

### ViMusic version

0.5.4

### Android version

Android 10

**Comment by vfsfitvnm** [comment] 2023-06-16 07:19
Would you provide more context? A stacktrace, a screen recording, etc...

**Comment by Gameronwork** [comment] 2023-06-16 16:08
> Would you provide more context? A stacktrace, a screen recording, etc...

Forgot to mention, when it closes all the songs loaded are gone from the list but the cache does not get deleted.

**Comment by vfsfitvnm** [comment] 2023-06-17 05:05
Thanks, this is a critical bug that and it must be fixed. If you are able to reproduce, then I need your help!

I'm going to drop another comment with more details in a few hours

**Comment by vfsfitvnm** [comment] 2023-06-17 09:41
Ok, I need:
- A screen recording (a video);
- To know whether it happens with a specific song only;
- The stacktrace (or the whole output of `adb logcat`) if you can.

**Comment by Gameronwork** [comment] 2023-06-18 06:30
> Ok, I need:
> - A screen recording (a video);
> - To know whether it happens with a specific song only;
> - The stacktrace (or the whole output of `adb logcat`) if you can.

Ok sure i will send it in a couple of hours.

**Comment by Gameronwork** [comment] 2023-06-19 18:14
> Ok, I need:
> - A screen recording (a video);
> - To know whether it happens with a specific song only;
> - The stacktrace (or the whole output of `adb logcat`) if you can.

https://github.com/vfsfitvnm/ViMusic/assets/102715816/4191640e-b9f0-420e-a66a-ead425d7f25f

Bro, it doesn't happen with specific song it happens with all but only on my device. I do have a backup so i load it every time it goes like that but when this bug happens and i use the app without the backup it works fine without closing.

**Comment by Gameronwork** [comment] 2023-06-19 18:15
And also my usb port is broken so i cannot send the adb logcat sorry 😞.

**Comment by vfsfitvnm** [comment] 2023-06-20 17:26
Alright, would you send your backup here? If that's whst causes che crash, I can reproduce.

PS: append `.txt` to the file name so that github lets you attach the file here

**Comment by vfsfitvnm** [comment] 2023-06-21 17:53
Thanks, but would you make it public?

**Comment by Gameronwork** [comment] 2023-06-22 15:42
> Thanks, but would you make it public?

Yeah I will.

**Comment by vfsfitvnm** [comment] 2023-06-22 17:24
Thanks, I could reproduce.

**Comment by vfsfitvnm** [comment] 2023-06-22 17:48
Ok it turns out the db was corrupted. I handle transactions and backups like shit, so it's hard to investigate, sadly.

However here's a repaired version:
[fix_vimusic_20230613220303.db.txt](https://github.com/vfsfitvnm/ViMusic/files/11837711/fix_vimusic_20230613220303.db.txt)

**Comment by vfsfitvnm** [comment] 2023-06-22 17:50
Closing in favor of #984

**Closed by vfsfitvnm** 2023-06-22 17:50 UTC
Labels: bug

**Comment by Gameronwork** [comment] 2023-06-23 09:07
> Ok it turns out the db was corrupted. I handle transactions and backups like shit, so it's hard to investigate, sadly.
> 
> However here's a repaired version:
> [fix_vimusic_20230613220303.db.txt](https://github.com/vfsfitvnm/ViMusic/files/11837711/fix_vimusic_20230613220303.db.txt)
> 

Thank you so much bro. And extremely sorry for all the trouble.
