### ISSUE TITLE
Database backup produces malformed file

### ISSUE THREAD

**Issue by zachvlat** [vfsfitvnm/ViMusic#406] opened 2022-10-11 10:34 UTC
### Steps to reproduce the bug

Pretty much what the title says. I have a backup of my playlists/favorites on the cloud, and when I downloaded the latest version of the app, the backups don't work.

### Expected behavior

The "Restore" button should restore old databases.

### Actual behavior

When the app closes it self and I open it up Playlists and Favorites are empty.

### ViMusic version

0.5.0

### Android version

Android 12

**Comment by vfsfitvnm** [comment] 2022-10-11 10:38
Can you share the backup?

**Comment by zachvlat** [comment] 2022-10-11 10:41
[vimusic_20221011132827.zip](https://github.com/vfsfitvnm/ViMusic/files/9754234/vimusic_20221011132827.zip)
I couldn't upload db files only zip.

**Comment by vfsfitvnm** [comment] 2022-10-11 10:53
The database file is corrupted ("_database disk image is malformed_"). Can you perform another backup?

**Comment by zachvlat** [comment] 2022-10-11 10:55
[vimusic_20221011135411.zip](https://github.com/vfsfitvnm/ViMusic/files/9754373/vimusic_20221011135411.zip)
i hope this works.

**Comment by vfsfitvnm** [comment] 2022-10-11 11:00
Nope, it is corrupted, too.
So, either the backup fails (do you have enough storage?) or the zipping is faulty. You can avoid the zipping by replacing the extension (`.db`) with `.txt`

**Comment by zachvlat** [comment] 2022-10-11 11:10
[vimusic_20221011135411.txt](https://github.com/vfsfitvnm/ViMusic/files/9754494/vimusic_20221011135411.txt)

**Comment by vfsfitvnm** [comment] 2022-10-11 11:16
Yeah, the backup fails somehow.

**Comment by vfsfitvnm** [comment] 2022-10-11 11:21
What's your device android version?

**Comment by zachvlat** [comment] 2022-10-11 11:25
> What's your device android version?

android 12 and the app version i m using is 0.4.3

**Comment by vfsfitvnm** [comment] 2022-10-11 12:29
Ok, I changed a little thing.

First, are you able to reproduce with [this](https://github.com/vfsfitvnm/ViMusic/actions/runs/3226015991) debug apk?
1. Open the app
2. Search for something
3. Perform a backup
4. Close app and clear app's data
5. Reopen the app and restore the database

Did it work?

After doing so, would you try [this](https://github.com/vfsfitvnm/ViMusic/actions/runs/3226808219) instead?

**Comment by zachvlat** [comment] 2022-10-11 12:42
Nope it didn't (both of them)

**Comment by vfsfitvnm** [comment] 2022-10-11 12:49
Nothing changed from 0.4.3 to 0.5.0 - I only upgraded the [room](https://developer.android.com/training/data-storage/room) version. However, just to make sure, you can use [this](https://github.com/vfsfitvnm/ViMusic/actions/runs/2989169802) 0.4.3 version.

**Comment by zachvlat** [comment] 2022-10-11 12:54
oh nothing still. I m thinking that maybe this was because i was using the binaries for the android auto implementation. maybe the android auto branch creates faulty databases.

**Comment by vfsfitvnm** [comment] 2022-10-11 13:06
It can't be. Are you using the same device? If so, how did you install the debug apks I sent you without uninstalling the apk (taken from [here](https://github.com/sriio/ViMusic/releases)) you already had?

**Comment by zachvlat** [comment] 2022-10-11 13:09
ofc i uninstall the previous version to put the other one. Yes I install them in the same device/same OS.

**Comment by vfsfitvnm** [comment] 2022-10-11 13:53
Oh, I gave you these apks because I thought you had the release apk installed! However it doesn't matter as we can't reproduce the issue anymore, so I'm gonna close this. I recovered most of the data of your corrupted database (press "Sync" to recover some of the playlists songs).

[vimusic_20221011155106.txt](https://github.com/vfsfitvnm/ViMusic/files/9756520/vimusic_20221011155106.txt)

**Closed by vfsfitvnm** 2022-10-11 13:53 UTC
Labels: bug, can't reproduce

**Comment by SebiderSushi** [comment] 2023-06-04 23:53
I believe i can reproduce this issue with my database and "Persistent Queue" enabled.

I've spent a whole while trying to come up with reproduction steps that result in a database that reliably reproduces this but while it seemed to reproduce the issue sometimes it was in no way as reliable as with my main database i've been using since last year.

<details><summary><b>This is the error message i'm getting</b></summary><pre>
06-05 01:06:40.599   458   477 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 0]
06-05 01:06:40.600   458   477 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 0]
06-05 01:06:40.674 14772 14797 E ROOM    : Invalidation tracker is initialized twice :/.
06-05 01:06:40.684 14772 14772 I ExoPlayerImpl: Init e4ec057 [AndroidXMedia3/1.0.0-beta02] [santoni, Redmi 4X, Xiaomi, 27]
06-05 01:06:40.693 14772 14793 E SQLiteLog: (11) database corruption at line 64173 of [0770363b30]
06-05 01:06:40.693 14772 14793 E SQLiteLog: (11) statement aborts at 2: [SELECT * FROM QueuedMediaItem] database disk image is malformed
06-05 01:06:40.693  2114  3146 D MediaSessionService: Media button session is changed to it.vfsfitvnm.vimusic/PlayerService (userId=0)
06-05 01:06:40.694 14772 14793 E SupportSQLite: Corruption reported by sqlite on database: a4.b@3de3b0.path
06-05 01:06:40.695 14772 14793 W SupportSQLite: deleting the database file: /data/user/0/it.vfsfitvnm.vimusic/databases/data.db
06-05 01:06:40.700 14772 14793 E AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
06-05 01:06:40.700 14772 14793 E AndroidRuntime: Process: it.vfsfitvnm.vimusic, PID: 14772
06-05 01:06:40.700 14772 14793 E AndroidRuntime: android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:846)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at t6.s.D(Unknown Source:38)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at t6.a.D(Unknown Source:2)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at w6.l.a(SourceFile:115)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at w6.l.e(SourceFile:13)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at androidx.compose.ui.platform.t.run(SourceFile:13)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
06-05 01:06:40.700 14772 14793 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
06-05 01:06:40.706  2114  2131 W ActivityManager:   Force finishing activity it.vfsfitvnm.vimusic/.MainActivity
06-05 01:06:40.709  2114 14841 W DropBoxManagerService: Dropping: data_app_crash (1164 > 0 bytes)
06-05 01:06:40.710 14772 14797 I zygote64: System.exit called, status: 0
06-05 01:06:40.710 14772 14797 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
</pre></details>

 - This database imports just fine as soon as i disable "Persistent Queue"
 - This database was previously exported on the same device. However, it could initially come from a different device but definitely has been in use without issues on this device for multiple months.
 - This error is reproducible when restoring the database on a second device (OnePlus X, LineageOS 18.1 android 11)
 - This error is reproducible after clearing ViMusic app data and turning on Persistent Queue.
 - There are no error messages when i open the database on my PC, either with `sqlite3` on the command line or [sqlitebrowser](https://sqlitebrowser.org/) GUI. `SELECT * FROM QueuedMediaItem` causes no errors and the table appears to be empty.
 - The Persistent Queue feature works perfectly fine when i disable it, restore the database, then turn it on again.
